### ISSUE TITLE
Companion app not showing all weakauras

### ISSUE THREAD

**Issue by Promixius** [WeakAuras/WeakAuras-Companion#1007]
**Operating System:**
- [x ] Windows
- [ ] Mac
- [ ] Linux

**Companion Version:**
```
3.22
```

**Companion App Console Log:**
```
electron/js2c/renderer_init.js:13 (electron) The remote module is deprecated. Use https://github.com/electron/remote instead.
log @ electron/js2c/renderer_init.js:13
app.0cb7ee51.js:1 validateWowpath
app.0cb7ee51.js:1 buildVersionList
2app.0cb7ee51.js:1 buildAccountList
app.0cb7ee51.js:1 updaterHandler: update-not-available
app.0cb7ee51.js:1 updaterHandler: checkForUpdates
app.0cb7ee51.js:1 promisesWagoCallsComplete
app.0cb7ee51.js:1 promisesWagoDataCallsComplete
app.0cb7ee51.js:1 writeAddonData
```

**WeakAuras Version:**
```
3.2.3 however when I run the console command it comes out with this trash:

Message: [string "print(WeakAuras.versionString) in-game."]:1: unexpected symbol near 'in'
Time: Mon Apr 12 11:38:33 2021
Count: 1
Stack: [string "print(WeakAuras.versionString) in-game."]:1: unexpected symbol near 'in'
[string "=[C]"]: ?
[string "=[C]"]: in function `RunScript'
[string "@Interface\FrameXML\ChatFrame.lua"]:2182: in function `?'
[string "@Interface\FrameXML\ChatFrame.lua"]:5094: in function `ChatEdit_ParseText'
[string "@Interface\FrameXML\ChatFrame.lua"]:4758: in function `ChatEdit_SendText'
[string "@Interface\FrameXML\ChatFrame.lua"]:4794: in function <Interface\FrameXML\ChatFrame.lua:4790>
[string "=[C]"]: in function `ChatEdit_OnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>
```

**WeakAuras Errors:**
```
You have no bugs, yay!
```

**Describe the bug**
Expected the WeakAuras Companion to show the list of Weakauras I have and see if I had some that needed an update but only 2 show up.

**To Reproduce**
1. Open companion app
2. Only 2 things show up expected at least 23

**Expected behavior**
I expected my weakauras to show up so I could see if they needed to update, for now it's back to the old manuel method.

**Screenshots**

**Include a .zip file containing:**
`%programfiles%\World of Warcraft\_retail_\WTF\Account\<AccountName>\SavedVariables\WeakAuras.lua`
AND
`%appdata%\weakauras-companion\
[config_and_wa_lua.zip](https://github.com/WeakAuras/WeakAuras-Companion/files/6295655/config_and_wa_lua.zip)

config.json`

**Comment by mrbuds** [comment]
There is an option to show all auras without updates, but it will still show only with a non-empty url field
