### ISSUE TITLE
Apple Silicon arm64 build 3.2.2 won't open

### ISSUE THREAD

**Issue by Slyrc** [WeakAuras/WeakAuras-Companion#1017]
**Operating System:**
- [ ] Windows
- [x ] Mac
- [ ] Linux

**Companion Version:3.2.2-arm64

**Describe the bug**

**To Reproduce**
Download the latest release 3.2.2 on an Apple Silicon Mac and open the App.

**Screenshots**
![Bildschirmfoto 2021-04-22 um 19 10 27](https://user-images.githubusercontent.com/62191325/115757946-e52ca280-a39e-11eb-99dd-7772b9505d9d.png)

Screenshot is in German. Translation: 
"WeakAuras Companion.app" is corrupted and cannot be opened. It is recommended to move the object to the trash.

**Comment by Stanzilla** [comment]
Can you try `xattr -rd com.apple.quarantine WeakAuras Companion.app`

**Comment by Slyrc** [comment]
Thx. This did the trick! I wonder why this did not happened with the intel build, this one just works out of the box.
