### ISSUE TITLE
Companion doesn't see new updates of some of my auras

### ISSUE THREAD

**Issue by Translitdk** [WeakAuras/WeakAuras-Companion#102]
**Operating System:**
- [ X] Windows
- [ ] Mac
- [ ] Linux

**Companion Version:**
```
Check the bottom left of the "About" panel in the app.
```
Not using it, but people reported that my auras do not appear as new version for them
**Companion App Console Log:**
```
Press Ctrl+Shift+I to open the console and copy-paste everything here
```

**WeakAuras Version:**
```
/run print(WeakAuras.versionString) in-game.
```
Happened on any version.
**WeakAuras Errors:**
```
1. Install https://mods.curse.com/addons/wow/BugSack
2. Install https://mods.curse.com/addons/wow/bug-grabber
3. Try to do whatever it is you're having a problem with again
4. Check your minimap for an icon that looks like a bag.  Is it green, or is it red?
   • GREEN
      • WeakAuras is working correctly.
      • Either you found a behavioral bug, or you are just doing it wrong :)
      • Explain the steps you took, and we will try to figure out what happened.
   • RED 
     • There are error messages. Click on the red bag to see them.
     • Copy & Paste here all of the error messages (there may be more than one, click the 'previous' button on the dialog to see previous ones
```
no errors
**Describe the bug**
Some of my auras like https://wago.io/Reaping https://wago.io/TalentSetup after i update them are not displayed in companion as it have new version. Also, if i update them from wago without companion they are not importing as update, instead they just importing as i never had this aura

Possible to happen why:
1)i duplicate one of auras, fix/exit it and then update it to the wago
2)it has a different name (spacebars at the end of it)
2)using TSU (less possible)
**To Reproduce**

**Expected behavior**
Expected to see new version avialible icon next to my auras when i update them on wago
**Screenshots**
https://i.imgur.com/mDyXpHr.png
https://i.imgur.com/RM46NJe.png
https://i.imgur.com/OS2I4Qu.png
https://i.imgur.com/cSkdUYt.png
**Include a .zip file containing:**
`%programfiles%\World of Warcraft\_retail_\WTF\Account\<AccountName>\SavedVariables\WeakAuras.lua`
AND
`%appdata%\weakauras-companion\config.json`

**Comment by mrbuds** [comment]
auras were moved after import
