### ISSUE TITLE
Updating a WeakAura fails with status 409

### ISSUE THREAD

**Issue by Dranni21312** [WeakAuras/WeakAuras-Companion#1052]
**Operating System:**
- [x] Windows
- [ ] Mac
- [ ] Linux

**Companion Version:**
3.3.1

**Companion App Console Log:**
Wowpath
app.13364ee2.js:1 buildVersionList
2app.13364ee2.js:1 buildAccountList
app.13364ee2.js:1 updaterHandler: update-not-available
app.13364ee2.js:1 updaterHandler: checkForUpdates
app.13364ee2.js:1 promisesWagoCallsComplete
data.wago.io/api/raw/encoded?id=l1T-_46zF:1 Failed to load resource: the server responded with a status of 409 ()
app.13364ee2.js:1 promisesWagoDataCallsComplete
app.13364ee2.js:1 no data received for 1v96NxSaE
app.13364ee2.js:1 no data received for W7W8cLAWn
app.13364ee2.js:1 no data received for InterruptTracker
app.13364ee2.js:1 writeAddonData
app.13364ee2.js:1 promisesWagoCallsComplete
data.wago.io/api/raw/encoded?id=l1T-_46zF:1 Failed to load resource: the server responded with a status of 409 ()
app.13364ee2.js:1 promisesWagoDataCallsComplete
app.13364ee2.js:1 no data received for 1v96NxSaE
app.13364ee2.js:1 no data received for W7W8cLAWn
app.13364ee2.js:1 no data received for InterruptTracker
app.13364ee2.js:1 writeAddonDa

**WeakAuras Version:**
3.3.0

**WeakAuras Errors:**
No errors

**Describe the bug**
The companion app fails to update the WeakAura found on https://wago.io/l1T-_46zF, returning error / status 409.

**To Reproduce**
1. Get the "Shadowlands Consumable Tracker / Readycheck - Clickable" weakaura found at https://wago.io/l1T-_46z
2. Start the companion app and see the 409 error.
3. Additional information - the companion app is trying to connect to the https://data.wago.io/api/raw/encoded?id=l1T-_46zF URL, and that returns {"error":"malicious_code_found"} JSON body.

**Expected behavior**
The update checking process should proceed without error.

**Screenshots**
![WA_409](https://user-images.githubusercontent.com/80227585/118559067-0f1e7e00-b72d-11eb-8704-ed4b56347518.png)

**Comment by wpsmark** [comment]
This was being blocked from some legacy code on Wago that wasn't actually needed anymore. It's working now.
