### ISSUE TITLE
DeprecationWarning when update for the app is available when running from cmd

### ISSUE THREAD

**Issue by JVemmer** [WeakAuras/WeakAuras-Companion#1053]
[config.zip](https://github.com/WeakAuras/WeakAuras-Companion/files/6515529/config.zip)

**Operating System:**
- [X] Windows
- [ ] Mac
- [ ] Linux

**Companion Version:**
```
3.3.1
```

**Companion App Console Log:**
```
electron/js2c/renderer_init.js:13 (electron) The remote module is deprecated. Use https://github.com/electron/remote instead.
log @ electron/js2c/renderer_init.js:13
app.13364ee2.js:1 validateWowpath
app.13364ee2.js:1 buildVersionList
app.13364ee2.js:1 buildAccountList
app.13364ee2.js:1 buildAccountList
app.13364ee2.js:1 updaterHandler: update-not-available
app.13364ee2.js:1 updaterHandler: checkForUpdates
app.13364ee2.js:1 promisesWagoCallsComplete
app.13364ee2.js:1 promisesWagoDataCallsComplete
app.13364ee2.js:1 writeAddonData
app.13364ee2.js:1 promisesWagoCallsComplete
app.13364ee2.js:1 promisesWagoDataCallsComplete
app.13364ee2.js:1 writeAddonData
app.13364ee2.js:1 promisesWagoCallsComplete
app.13364ee2.js:1 promisesWagoDataCallsComplete
app.13364ee2.js:1 writeAddonData
```

**WeakAuras Version:**
```
3.4.1
```

**WeakAuras Errors:**
```
This is not a WeakAuras issue. It is purely a companion app issue.
```

**Describe the bug**
When trying to run WeakAuras Companion from cmd, as part of a batch script on Windows, I get a DeprecationWarning about Buffer(), **if there is an update available**.
I have tested variations of the command shown in this ticket, but have only posted the one that includes every single parameter tested. No variation I tested, produced a different result.
The goal of my attempts where to create a batch file, that will launch a bunch of game related applications, such as WeakAuras Companion, WowUp, etc., when clicked. The command checks if the process is running, and only tries to launch the process, if it is not already running.
Surprisingly, the error is thrown, even when cmd has been instructed to send all output to "nul".
The error is:

> (node:2720) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use weakauras-companion --trace-deprecation ... to show where the warning was created)

**To Reproduce**
1. Install an old version of WeakAuras companion.
2. Create a batch-file (for simplicity, let's call it test.sh)
3. Put the following command in that file: `TASKLIST | FIND /i "WeakAuras Companion" > nul || START "" "%LOCALAPPDATA%\Programs\weakauras-companion\WeakAuras Companion.exe" > nul 2> nul`
4. Double-click the file.

**Expected behavior**
I expect the app to launch, just as it does when there is no update available.

**Include a .zip file containing:**
`%programfiles%\World of Warcraft\_retail_\WTF\Account\<AccountName>\SavedVariables\WeakAuras.lua`
AND
`[config.zip](https://github.com/WeakAuras/WeakAuras-Companion/files/6515489/config.zip)`

**Comment by Stanzilla** [comment]
Not really a bug but thanks for noticing!
