### ISSUE TITLE
APP cannot be opened in macOS Monterey

### ISSUE THREAD

**Issue by TripLeamon** [WeakAuras/WeakAuras-Companion#1070]
Weakauras-Companion (v3.3.3-mac-x64) cannot be opened at the Mac(Intel) after updating macOS Monterey(12.0 Beta). 
Cannot open after reinstalling the app.

**Comment by TripLeamon** [comment]
> Weakauras-Companion (v3.3.3-mac-x64) cannot be opened at the Mac(Intel) after updating macOS Monterey(12.0 Beta).
> Cannot open after reinstalling the app.

**Comment by Stanzilla** [comment]
Any error messages or so in the console app?

**Comment by mrbuds** [comment]
no update from reporter
