### ISSUE TITLE
App not sending new Weakauras to game

### ISSUE THREAD

**Issue by comiluv** [WeakAuras/WeakAuras-Companion#1166]
**Operating System:**
- [V] Windows
- [ ] Mac
- [ ] Linux

**Companion Version:**
```
3.3.4
```

**Companion App Console Log:**
```
electron/js2c/renderer_init.js:13 (electron) The remote module is deprecated. Use https://github.com/electron/remote instead.
log @ electron/js2c/renderer_init.js:13
app.2e94e2cb.js:95 validateWowpath
app.2e94e2cb.js:95 buildVersionList
app.2e94e2cb.js:95 buildAccountList
app.2e94e2cb.js:1 Plater not found at C:\Program Files (x86)\World of Warcraft\_retail_\Interface\AddOns
app.2e94e2cb.js:95 buildAccountList
app.2e94e2cb.js:1 Plater not found at C:\Program Files (x86)\World of Warcraft\_retail_\Interface\AddOns
app.2e94e2cb.js:17 promisesWagoCallsComplete
app.2e94e2cb.js:17 promisesWagoDataCallsComplete
app.2e94e2cb.js:17 writeAddonData
app.2e94e2cb.js:17 updaterHandler: update-not-available
app.2e94e2cb.js:17 updaterHandler: checkForUpdates
app.2e94e2cb.js:17 writeAddonData
app.2e94e2cb.js:17 on complete
app.2e94e2cb.js:17 index: 0
app.2e94e2cb.js:17 writeAddonData
internal/fs/utils.js:307 Uncaught Error: ENOENT: no such file or directory, stat 'C:\Program Files (x86)\World of Warcraft\_retail_\WTF\Account\COMILUV\SavedVariables\WeakAurasCompanion.lua'
    at statSync (fs.js:1086)
    at Object.e.statSync (electron/js2c/asar_bundle.js:5)
    at FSWatcher.<anonymous> (app.2e94e2cb.js:1)
    at FSWatcher.emit (events.js:315)
    at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:186)
```

**WeakAuras Version:**
```
3.7.2
```

**WeakAuras Errors:**
```
   • GREEN
```

**Describe the bug**
WeakAuras companion app does not receive and push a new Weakauras to the game

**To Reproduce**
1. Open wago.io in web browser
2. Select any Weakaura, used https://wago.io/Afenar_Druid for the example
3. Click on Send to Desktop App box in the right upper portion of the browser windows
4. Click on Weakauras Companion in the pop up box
5. Click Install Weakaura from the pop up box which is located in the right lower portion of the pop up box
6. Weakauras Companion app shows "New WeakAuras ready to install:..." message and "Reload World of Warcraft..." message
7. Start World of Warcraft
8. Log in to any character with both Weakauras and WeakAuras Companion addon enabled
9. type /wa
10. You don't see the new Weakaura installed.

**Expected behavior**
The new Weakaura appears

**Screenshots**
In game /wa screenshot
![WoWScrnShot_100521_120819](https://user-images.githubusercontent.com/19642705/135953928-493a9dcb-dfdd-495f-a69b-09a6505cbc65.jpg)

**Include a .zip file containing:**
`%programfiles%\World of Warcraft\_retail_\WTF\Account\<AccountName>\SavedVariables\WeakAuras.lua`
AND
`%appdata%\weakauras-companion\config.json
`

[attached.zip](https://github.com/WeakAuras/WeakAuras-Companion/files/7282497/attached.zip)

**Comment by mrbuds** [comment]
Workflow for new imported auras is not very clear, data is lost if toast is closed, keep toast open and it should show in app.
Sorry if i didn't answer sooner, general help is best answered on weakauras discord
