### ISSUE TITLE
Unable to select the World of Warcraft folder

### ISSUE THREAD

**Issue by Xozus1234** [WeakAuras/WeakAuras-Companion#1251]
**Operating System:**
- [X] Windows
- [ ] Mac
- [ ] Linux

**Companion Version:**
```
Check the bottom left of the "About" panel in the app.
3.3.4

**Companion App Console Log:**
```
Press Ctrl+Shift+I to open the console and copy-paste everything here
Ctrl+Shift+I takes a screen shot, there is nothing to copy/paste here

**WeakAuras Version:**
```
/run print(WeakAuras.versionString) in-game.
```

**WeakAuras Errors:**
```
1. Install https://mods.curse.com/addons/wow/BugSack
2. Install https://mods.curse.com/addons/wow/bug-grabber
3. Try to do whatever it is you're having a problem with again
4. Check your minimap for an icon that looks like a bag.  Is it green, or is it red?
   • GREEN
      • WeakAuras is working correctly.
      • Either you found a behavioral bug, or you are just doing it wrong :)
      • Explain the steps you took, and we will try to figure out what happened.
   • RED 
     • There are error messages. Click on the red bag to see them.
     • Copy & Paste here all of the error messages (there may be more than one, click the 'previous' button on the dialog to see previous ones
```

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
Screenshot shows the valid wow folder, and WA not liking it.
![unknown_2022 01 07-15 32](https://user-images.githubusercontent.com/97316451/148610206-4df3c993-26ed-40ab-adb3-53d5810dd8ed.png)

**Include a .zip file containing:**
`%programfiles%\World of Warcraft\_retail_\WTF\Account\<AccountName>\SavedVariables\WeakAuras.lua`
AND
`%appdata%\weakauras-companion\config.json`

**Comment by mrbuds** [comment]
Looks like you selected wrong folder, please use discord for general help and keep github tickets for bugs
