### ISSUE TITLE
WeakAura Companion ARM Version not starting at all 

### ISSUE THREAD

**Issue by rionshin** [WeakAuras/WeakAuras-Companion#1332]
**Operating System:**
- [ ] Windows
- [ X] Mac
- [ ] Linux

**Companion Version:**
```
3.3.4
```

**Companion App Console Log:**
```
Press Ctrl+Shift+I to open the console and copy-paste everything here
```

**WeakAuras Version:**
```
/run print(WeakAuras.versionString) in-game.
```
 

**Describe the bug**
I am running MAC OS Monterey on M1 Max Apple silicon - MAC Studio,  the application do not start at all and OS is saying that app is corrupted and cannot be started.  This is happening only with ARM Version, the x64 is installed with no issue but crashing on start with Rosetta error. 

**To Reproduce**
On Run return error that app is damaged (error attached)

Max x64 version is not working as well, crashing on launch with crash report attached.)

**Expected behavior**
app to run 
<img width="884" alt="Screenshot 2022-04-09 at 13 36 05" src="https://user-images.githubusercontent.com/41396180/162568339-d2ad652f-75f4-4208-a791-04d121136a2d.png">

**Screenshots**
Attache screenshot from ARM Issue 

I also attached the log from x64 app which do not start as well

**Comment by Stanzilla** [comment]
I do not see an attached log, it works fine for me on an Intel Mac on Monterey, I don't have an M1 one to test.

**Comment by rionshin** [comment]
The x64 version is now working on Roseta , i uninstall completely M1 version and remove all files associated with it and then install x64 version and it is working now. However the M1 version is not working at all and failing with damaged  app error - i install it on another mac and same error.

**Comment by mwd89** [comment]
Just posting to confirm rionshin's findings: WACs macOS ARM Version does not run on Apple Silicon, while the macOS x64 Version does and thus providing a currently viable workaround. Logs from the app can't be provided, as it crashes before it starts. If system logs are required, please specify from what source. But since you can't troubleshoot without an M1 Mac, this might be in vain anyway. 

Regardless of that: Thanks for providing WAC. Very useful!

**Comment by rionshin** [comment]
Latest release is failing as well with following error: 

/Applications/WeakAuras Companion.app/Contents/Resources/app.asar/node_modules/sharp/lib/sharp.js:31 Uncaught Error: 
Something went wrong installing the "sharp" module

dlopen(/Applications/WeakAuras Companion.app/Contents/Resources/app.asar.unpacked/node_modules/sharp/build/Release/sharp-darwin-arm64v8.node, 0x0001): Library not loaded: @rpath/libvips-cpp.42.dylib
  Referenced from: /Applications/WeakAuras Companion.app/Contents/Resources/app.asar.unpacked/node_modules/sharp/build/Release/sharp-darwin-arm64v8.node
  Reason: tried: '/Applications/WeakAuras Companion.app/Contents/Resources/app.asar.unpacked/node_modules/sharp/build/Release/../.././vendor/8.12.2/darwin-arm64v8/lib/libvips-cpp.42.dylib' (no such file), '/Applications/WeakAuras Companion.app/Contents/Resources/app.asar.unpacked/node_modules/sharp/build/Release/../.././vendor/8.12.2/darwin-arm64v8/lib/libvips-cpp.42.dylib' (no such file), '/Applications/WeakAuras Companion.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libvips-cpp.42.dylib' (no such file), '/Applications/WeakAuras Companion.app/Contents/Frameworks/WeakAuras Companion Helper (Renderer).app/Contents/MacOS/../../../libvips-cpp.42.dylib' (no such file), '/usr/local/lib/libvips-cpp.42.dylib' (no such file), '/usr/lib/libvips-cpp.42.dylib' (no such file)

Possible solutions:
- Install with verbose logging and look for errors: "npm install --ignore-scripts=false --foreground-scripts --verbose sharp"
- Install for the current darwin-arm64v8 runtime: "npm install --platform=darwin --arch=arm64v8 sharp"
- Consult the installation documentation: https://sharp.pixelplumbing.com/install
    at Object.<anonymous> (/Applications/WeakAuras Companion.app/Contents/Resources/app.asar/node_modules/sharp/lib/sharp.js:31:9)
    at Object.<anonymous> (/Applications/WeakAuras Companion.app/Contents/Resources/app.asar/node_modules/sharp/lib/sharp.js:34:3)
    at Module._compile (node:internal/modules/cjs/loader:1118:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at i._load (node:electron/js2c/renderer_init:33:356)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)

**Comment by mrbuds** [comment]
> Latest release 4.0.1 is failing as well with following error:
> 
> /Applications/WeakAuras Companion.app/Contents/Resources/app.asar/node_modules/sharp/lib/sharp.js:31 Uncaught Error: Something went wrong installing the "sharp" module
> 

Can you try this version https://github.com/WeakAuras/WeakAuras-Companion/suites/6866464821/artifacts/265479908 ?

**Comment by TripLeamon** [comment]
Same as 4.0.1, 4.0.3 is still failing as well with the same error: 
Uncaught Error: 
Applications/WeakAuras Companion.app/Contents/Resources/app.asar/node_modules/sharp/lib/sharp.js:31 

Something went wrong installing the "sharp" module

dlopen(/Applications/WeakAuras Companion.app/Contents/Resources/app.asar.unpacked/node_modules/sharp/build/Release/sharp-darwin-arm64v8.node, 0x0001): Library not loaded: @rpath/libvips-cpp.42.dylib
  Referenced from: /Applications/WeakAuras Companion.app/Contents/Resources/app.asar.unpacked/node_modules/sharp/build/Release/sharp-darwin-arm64v8.node
  Reason: tried: '/Applications/WeakAuras Companion.app/Contents/Resources/app.asar.unpacked/node_modules/sharp/build/Release/../.././vendor/8.12.2/darwin-arm64v8/lib/libvips-cpp.42.dylib' (no such file), '/Applications/WeakAuras Companion.app/Contents/Resources/app.asar.unpacked/node_modules/sharp/build/Release/../.././vendor/8.12.2/darwin-arm64v8/lib/libvips-cpp.42.dylib' (no such file), '/Applications/WeakAuras Companion.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libvips-cpp.42.dylib' (no such file), '/Applications/WeakAuras Companion.app/Contents/Frameworks/WeakAuras Companion Helper (Renderer).app/Contents/MacOS/../../../libvips-cpp.42.dylib' (no such file), '/usr/local/lib/libvips-cpp.42.dylib' (no such file), '/usr/lib/libvips-cpp.42.dylib' (no such file)

Possible solutions:
- Install with verbose logging and look for errors: "npm install --ignore-scripts=false --foreground-scripts --verbose sharp"
- Install for the current darwin-arm64v8 runtime: "npm install --platform=darwin --arch=arm64v8 sharp"
- Consult the installation documentation: https://sharp.pixelplumbing.com/install
    at Object.<anonymous> (/Applications/WeakAuras Companion.app/Contents/Resources/app.asar/node_modules/sharp/lib/sharp.js:31:9)
    at Object.<anonymous> (/Applications/WeakAuras Companion.app/Contents/Resources/app.asar/node_modules/sharp/lib/sharp.js:34:3)
    at Module._compile (node:internal/modules/cjs/loader:1118:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at i._load (node:electron/js2c/renderer_init:33:356)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)

**Comment by mrbuds** [comment]
Can you guys test this build https://github.com/WeakAuras/WeakAuras-Companion/suites/6886979176/artifacts/266777496 ?

**Comment by TripLeamon** [comment]
> Can you guys test this build https://github.com/WeakAuras/WeakAuras-Companion/suites/6886979176/artifacts/266777496 ?

Thanks for helping. 
This version can be used normally without any errors.

**Comment by paralovosca** [comment]
> Can you guys test this build https://github.com/WeakAuras/WeakAuras-Companion/suites/6886979176/artifacts/266777496 ?

I am having the same issue but link to test build returns 404.

**Comment by choonies** [comment]
> Can you guys test this build https://github.com/WeakAuras/WeakAuras-Companion/suites/6886979176/artifacts/266777496 ?

Thank you! Was also having an issue after updating where the newest version would not work on my M1 Mac, but this test build works!! :)

**Comment by mwd89** [comment]
I can confirm that the latest build of 4.0.3 also works on ARM-Macs. Thanks a lot!

> > Can you guys test this build https://github.com/WeakAuras/WeakAuras-Companion/suites/6886979176/artifacts/266777496 ?
> 
> I am having the same issue but link to test build returns 404.

Great, I can confirm as will that the latest build of 4.0.3 works with ARM-Macs. Thanks a lot!

**Comment by mrbuds** [comment]
4.0.4 version was release with this fix, thanks guys for helping test it!
