### ISSUE TITLE
Option for Close to minimize application rather than close

### ISSUE THREAD

**Issue by jsutan** [WeakAuras/WeakAuras-Companion#1440]
Please add an option to allow the companion app to minimize to tray when closing it using the Close button rather than closing the application entirely. WeakAuras Companion is an application that generally favors being open all the time in the background so I'd argue that this should be default behavior but even if there was a preference similar to what most applications have it would be better than current state.

**Comment by mrbuds** [comment]
What you are asking is a [deceptive design](https://www.deceptive.design) that we would consider if we had benefits to trick users into thinking it's closed when it is not, for example for showing ads or spying on you. I would not trust an app with this behavior and i'd prefer not add this "functionality".

**Comment by derekschrock** [comment]
> What you are asking is a [deceptive design](https://www.deceptive.design) that we would consider if we had benefits to trick users into thinking it's closed when it is not, for example for showing ads or spying on you. I would not trust an app with this behavior and i'd prefer not add this "functionality".

If this is true then why do you have Start minimized?  It's equally as deceptive if not worse.   Should we not trust you?  However, like the requested feature it's opt in there's deception to be had.
