### ISSUE TITLE
No option to update the WeakAura Companion stand alone software. 

### ISSUE THREAD

**Issue by Spaceherpe** [WeakAuras/WeakAuras-Companion#1444]
I was not able to locate any option in the Companion GUI that would allow me to update the Companion. My computer was showing regular notifications that it needed to be updated, which required me to go to the website and download a completely new version of the software, vice being able to simply update it via the companion itself.

**Comment by mrbuds** [comment]
You didn't mention which version you had installed, but for current version when there is an update you can click the notification to download new version.
