### ISSUE TITLE
Weakauras no longer loading in game with new app

### ISSUE THREAD

**Issue by reaper082** [WeakAuras/WeakAuras-Companion#1495]
**Operating System:**
- [x ] Windows
- [ ] Mac
- [ ] Linux

**Companion Version:**
```
Check the bottom left of the "About" panel in the app.
```

**Companion App Console Log:**
```
Press Ctrl+Shift+I to open the console and copy-paste everything here
```

**WeakAuras Version:**
```
/run print(WeakAuras.versionString) in-game.
```

**WeakAuras Errors:**
```
1. Install https://mods.curse.com/addons/wow/BugSack
2. Install https://mods.curse.com/addons/wow/bug-grabber
3. Try to do whatever it is you're having a problem with again
4. Check your minimap for an icon that looks like a bag.  Is it green, or is it red?
   • GREEN
      • WeakAuras is working correctly.
      • Either you found a behavioral bug, or you are just doing it wrong :)
      • Explain the steps you took, and we will try to figure out what happened.
   • RED 
     • There are error messages. Click on the red bag to see them.
     • Copy & Paste here all of the error messages (there may be more than one, click the 'previous' button on the dialog to see previous ones
```

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Include a .zip file containing:**
`%programfiles%\World of Warcraft\_retail_\WTF\Account\<AccountName>\SavedVariables\WeakAuras.lua`
AND
`%appdata%\weakauras-companion\config.json`

**Comment by reaper082** [comment]
I was just letting you know that the new app has erased all the weak auras
I had installed and I had to start from scratch. That way yall know for the
future. I just spent 2 hours redoing them all, and I'm sure I forgot some
but I'll figure that out when I get to it.

**Comment by InfusOnWoW** [comment]
No it didn't. The companion does not touch your WeakAuras settings.

But more importantly, if you are using the companion app, that automatically creates backups of you WeakAuras settigns.

**Comment by reaper082** [comment]
Ok ill have to look into that, thank you for the information. The companion
app says it needs an update but will not do it, should I just attempt it
later?
