### ISSUE TITLE
WeakAuras Companion 4.0.4 "Error in updater download"

### ISSUE THREAD

**Issue by Yihungdi** [WeakAuras/WeakAuras-Companion#1524]
I'm having an issue with the latest UPDATE to 4.0.4
After the download completes my download folder is showing "Unconfirmed 476137.crdownload"
Also my browser reports this: WeakAuras-Companion-4.0.4.exe isn't commonly downloaded. Make sure you trust WeakAuras Companion, and it wants me to delete the file.
I have attempted to update to this version for the past few weeks and nothing changes.
I have in my download folder versions 4.0.2 and 4.0.3 and they are showing as normal download file.
Why is this one different? Is it because the link is showing that this Fixes Mac ARM version and we are to just forget about this version?

**Comment by Yihungdi** [comment]
I have tried with my default browser Microsoft Edge latest version and Firefox latest version and get the same issue with bothj……

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by mrbuds** [comment]
Do you download it from https://weakauras.wtf/ ?

**Comment by Yihungdi** [comment]
Yes and get the same thing

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by Stanzilla** [comment]
Sounds like it's just Microsoft Defender again

**Comment by Yihungdi** [comment]
This is what Edge is reporting

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by Yihungdi** [comment]
Ben Staneck,

JUST A FYI,
Hey Ben I was finally able to do a update to version 4.0.4 thru Firefox browser.
For some reason in my prior attempts Microsoft (defender) was blocking updating thru it, but
yesterday I copied the link from Edge browser and put it in my Firefox browser
and was able to complete the download (finally) with out Microsoft (defender not allowing the
download to complete) stating that the author was not valid, and when I went to install Microsoft
(defender) again attempted to stop it but there was a line in the toast window that said did I want to continue
and I did and the install went thru.

Again this is just a FYI, thanks for all you did,

G Taylor (bloodwulf)



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by Yihungdi** [comment]
Benjamin,

There needs to be another update to this project as when I run the WeakAuras Companion it changes the interface
ID to 90205 and the latest for the game is 90207. If I don’t change this in the TOC the game reports that WeakAuras
Is OUT OF DATE. Once this is changed to 90207 the OUT of DATE is removed….

Thanks,
Yihungdi

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
