### ISSUE TITLE
I want to cancel ignore update.

### ISSUE THREAD

**Issue by php-nalcoder** [WeakAuras/WeakAuras-Companion#1543]
I want to cancel ignore update .
However, there is no such feature in the in-game add-on or companion app.
Can you please add this feature?

**Comment by Quietpaw** [comment]
Issue still exists. I cannot figure out how to re-enable updates for a weakaura that's been changed to "updates disabled"

**Comment by kuliani** [comment]
For those of us that want the feature but can't wait, here's the workaround:

Open your WeakAuras.lua file in your WorldofWarcraft/retail/WTF/Account/(account name)/SavedVariable folder using a text editor, like Notepad or Notepad++.

Find all instances of **_["ignoreWagoUpdate"] = true_** and change the "true" to "false".

**Comment by mrbuds** [comment]
https://github.com/WeakAuras/WeakAuras2/pull/4443 fixed it by adding an option to Information tab
