### ISSUE TITLE
Start WA Companion in CMD

### ISSUE THREAD

**Issue by Krelus** [WeakAuras/WeakAuras-Companion#161]
Sistem: Win 10 ×64
WA Companion: 1.1.7
If i start WAC (WA Companion) in CMD i get:
D:\>"C:\Users\****\AppData\Local\Programs\weakauras-companion\WeakAuras Companion.exe"

 [36m09:27:22.185[0m ÔÇ║ App starting...[0m
[36m09:27:22.560[0m ÔÇ║ Checking for update[0m
[36m09:27:25.383[0m ÔÇ║ Update for version 1.1.7 is not available (latest version: 1.1.7, downgrade is allowed).[0m
[0m09:27:25.384[0m ÔÇ║ checkForUpdatesAndNotify called, downloadPromise is null[0m

and if i close CMD then the WAC close to  :(
------
Start whit shortcut is normal. :)
--- 
Have a nice day

**Comment by mrbuds** [comment]
You are one day too early for april fool joke :D

**Comment by Krelus** [comment]
hojla

https://krelus.tinytake.com/sf/MzQzMDQxNV8xMDI2OTM1OQ

??  :D

**Comment by Stanzilla** [comment]
This is how Windows works, get used to it :)

**Comment by Krelus** [comment]
lol

**Comment by Stanzilla** [comment]
as you can see in the video, the process is still running after start because it is waiting for debug output to the console
and if you kill a cmd with a running process, the process dies
same as hitting ctrl c
