### ISSUE TITLE
WeakAuras Companion cannot be closed. 

### ISSUE THREAD

**Issue by swisswass** [WeakAuras/WeakAuras-Companion#1627]
When I tried to update the application it said it I had to close it before installing. I closed it and retried. Then I got this message. Ive restarted my computer, uninstalled the application, deleted and redownloaded the companion setup multiple times but when I try to install it I always get the same message.
![Weakauras](https://user-images.githubusercontent.com/117245221/199382181-7ee8b85d-5269-4565-8b17-62305177f056.jpg)

**Comment by mrbuds** [comment]
It look like an old issue we have already seen https://github.com/electron-userland/electron-builder/issues/4057
Try use regedit.exe and remove references to WeakAurasCompanion in `Computer\HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Uninstall`

**Comment by swisswass** [comment]
> It look like an old issue we have already seen [electron-userland/electron-builder#4057](https://github.com/electron-userland/electron-builder/issues/4057) Try use regedit.exe and remove references to WeakAurasCompanion in `Computer\HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Uninstall`

Unfortunately cleaning out the whole uninstall folder did nothing and I still get the same issue.

**Comment by maxingan2412** [comment]
I encountered the issue too, and also  cleaning out the whole uninstall folder did nothing

**Comment by Stanzilla** [comment]
Not much we can do about that, sadly
