### ISSUE TITLE
ingame addon is out of date

### ISSUE THREAD

**Issue by steveredden** [WeakAuras/WeakAuras-Companion#1636]
**Operating System:**
- [ ] Windows
- [ ] Mac
- [ ] Linux
- [x] N/A

**Companion Version:**
N/A

**Companion App Console Log:**
N/A

**WeakAuras Version:**
```
5.1.1
```

**WeakAuras Errors:**
```
N/A
```

**Describe the bug**
in `<mydir>\World of Warcraft\_retail_\Interface\AddOns\WeakAurasCompanion\WeakAurasCompanion-Mainline.toc` ...
 
```
## Interface: 90207
## Title: Wago App Companion
## Author: The wago team
## Version: 1.0.0
## DefaultState: Enabled
## LoadOnDemand: 0
## OptionalDependencies: WeakAuras
```

`Interface` needs to be `100000`+ in order to not be considered out of date.

Oddly, I don't see this file anywhere on github, so starting here...

**Comment by Stanzilla** [comment]
That's the wago app not wa companion
