### ISSUE TITLE
Weakaura won't update

### ISSUE THREAD

**Issue by drrob8091** [WeakAuras/WeakAuras-Companion#1689]
**Operating System:**
- [ ] Windows
- [ ] Mac
- [ ] Linux

**Companion Version:**
```
Check the bottom left of the "About" panel in the app.
```

**Companion App Console Log:**
```
Press Ctrl+Shift+I to open the console and copy-paste everything here
```

**WeakAuras Version:**
```
/run print(WeakAuras.versionString) in-game.
```

**WeakAuras Errors:**
```
1. Install https://mods.curse.com/addons/wow/BugSack
2. Install https://mods.curse.com/addons/wow/bug-grabber
3. Try to do whatever it is you're having a problem with again
4. Check your minimap for an icon that looks like a bag.  Is it green, or is it red?
   • GREEN
      • WeakAuras is working correctly.
      • Either you found a behavioral bug, or you are just doing it wrong :)
      • Explain the steps you took, and we will try to figure out what happened.
   • RED 
     • There are error messages. Click on the red bag to see them.
     • Copy & Paste here all of the error messages (there may be more than one, click the 'previous' button on the dialog to see previous ones
```

**Describe the bug**
The weakaura Luxthos - Monk - Dragonflight keeps telling me there's an update. I update it in-game and then it stays there like it needs to be updated again. I have deleted the weakaura and reinstalled it but it still has the same issue. 

**To Reproduce**
1. Go to 'update'
2. Click on 'update'
4. See error - it doesn't update. It still says it needs to update. You can do it repeatedly. 
![Screenshot (81)](https://user-images.githubusercontent.com/36579133/208854736-5c623a57-c5bc-4d39-9253-10bc29f3ddf5.png)
![Screenshot (83)](https://user-images.githubusercontent.com/36579133/208854750-5a10dff9-e4dc-49ed-a647-68490c970de3.png)

**Expected behavior**

**Screenshots**

**Include a .zip file containing:**
`%programfiles%\World of Warcraft\_retail_\WTF\Account\<AccountName>\SavedVariables\WeakAuras.lua`
AND
`%appdata%\weakauras-companion\config.json`

**Comment by mrbuds** [comment]
This ticket is missing too much important information.

- The 2 files asked to be included are not included, please also include in addition your WeakAurasCompanion addon folder.
- Reproduction steps are not reproducible, if i "Go to 'update'" i don't have this aura installed.
- "See error - it doesn't update" i don't see a Lua error, and i don't know if you have one because you skipped the part of the issue template where it's asked to installed bugsack & buggrabber and give Lua error if there is one
