### ISSUE TITLE
MacOS 10.14.6 Error

### ISSUE THREAD

**Issue by Triskadion** [WeakAuras/WeakAuras-Companion#1704]
App does not run in this version of Mac OS. App runs, but only a line is visible on screen. Crash Log attached

[WeakAuras Companion Helper (Renderer)_2023-01-02-131707.crash.zip](https://github.com/WeakAuras/WeakAuras-Companion/files/10333241/WeakAuras.Companion.Helper.Renderer._2023-01-02-131707.crash.zip)

**Comment by Stanzilla** [comment]
Hey there, that is a pretty old version of macOS and no longer supported by us.
