### ISSUE TITLE
How to remove Weakauras from the companion App

### ISSUE THREAD

**Issue by W00KIEE** [WeakAuras/WeakAuras-Companion#1725]
Hey all there is no uninstall option to remove the weakaruas from your compainon list how do i go about removing these?

**Comment by Stanzilla** [comment]
You remove them in game, in WeakAuras itself

**Comment by W00KIEE** [comment]
There is no option to remove you can see the imgur. The Afenar | Warlock | Dragonflight is already installed but still shows need to be installed i've removed it reinstalled it tried updating it cannot get rid of it i also have some old hunter Weak auras i removed from my weakauras in game and they still show up in the companion app.
https://imgur.com/a/TM8AXmd

**Comment by mrbuds** [comment]
This is different from the original question.

In app you can either clean ready for install auras by clicking the animated glowing green arrow on bottom right of the window
Or restart app

If that doesn't help, it means that an other app than weakauras companion wants to install this aura (wago app, cursebreaker, ..) and you will have to disable or delete their addon.

**Comment by W00KIEE** [comment]
I dont have another app and my compainon app doesn't have the arrow for this it just says up to date in the main panel.

**Comment by W00KIEE** [comment]
I think i may have found the issue i still have weakaura companion 2.0.4 installed somehow but when i go to unistall my computer says its not there i've tried to reinstall the 2.0.4 version to see if i could fully remove it and it just sits stuck halfway on the loading/installing bar
