### ISSUE TITLE
Not updating

### ISSUE THREAD

**Issue by zalidthebur** [WeakAuras/WeakAuras-Companion#1766]
**Operating System:**
- [ X] Windows
- [ ] Mac
- [ ] Linux

**Companion Version:**
``` 
4.1.5
```

**Companion App Console Log:**
```
Press Ctrl+Shift+I to open the console and copy-paste everything here
``` No Companion App Console Log on About panel. Shortcut does nothing.

**WeakAuras Version:**
```Version: 5.3.7
```

**Describe the bug**
The companion "Fetch Updates" does not work. I click it. It spins and nothing is updated.

**Expected behavior**
For the companion to update weakauras that are "update ready".

**Include a .zip file containing:**
`%programfiles%\World of Warcraft\_retail_\WTF\Account\<AccountName>\SavedVariables\WeakAuras.lua`
AND
`%appdata%\weakauras-companion\config.json`
[WeakAuras.zip](https://github.com/WeakAuras/WeakAuras-Companion/files/10834160/WeakAuras.zip)
[config.zip](https://github.com/WeakAuras/WeakAuras-Companion/files/10834164/config.zip)

**Comment by mrbuds** [comment]
ctrl+shift+i should open a window like this 

![image](https://user-images.githubusercontent.com/189656/221424674-86ef3568-d56f-4cac-89bc-d9a7dca01102.png)

**Comment by zalidthebur** [comment]
Ah. I see what happened. I mixed up the previous command "Check the bottom left of the "About" panel in the app." with the shortcut keypresses. It does not work on the About page, but worked on the home page.
I've also now checked the "?" tab and see I need to have this running whilst in game. So now I understand how it works and there is no bug :-)
