### ISSUE TITLE
Export WeakAuras List

### ISSUE THREAD

**Issue by yankikucuk** [WeakAuras/WeakAuras-Companion#1816]
It would be nice to export the used weakauras as a list. After the PC format or the computer was changed, we could continue from where we left off by just importing. We would save time. Also backup files can be beckupable or have changeable directory.

**Comment by InfusOnWoW** [comment]
There's an upper limit to the size of imports, because of technical limitations that are unlikely to change.

Mass importing like you suggest would run into these limitations.

A backup of the actual settings file is much easier than trying to import or export all auras.

**Comment by yankikucuk** [comment]
Wow! I think this has to be the fastest closed issue with no discussions. Please let me explain some of the major points about your thoughts.

By exporting the Weakauras I didn't mean to export them with all the base codes, settings etc. I mean exporting them as a simple text file with just wago links.

for example:
```txt 
https://wago.io/some/aura/link
https://wago.io/some/aura/link2
https://wago.io/some/aura/link3
https://wago.io/some/aura/link4
https://wago.io/some/aura/link5
```

**Comment by InfusOnWoW** [comment]
What's the benefit of that vs just backing up the settings file? 

Your stated use case "After the PC format or the computer was changed, we could continue from where we left off by just importing.", is easily handled by backing up the actual settings files.

**Comment by yankikucuk** [comment]
🌟 Takes up much less space
🌟 If there are updated aura versions, no further action is required as it will pull the data from wago during import.
🌟 New lines can be easily added or removed as it is a simple .txt file.
🌟 They do not contain complex data. Readable and understandable to the end user.

I'm not saying that backup files are unnecessary. I just underline that it is much easier and simpler for the user to be this way. An idea where the two methods can be used together can also be considered.

**Comment by InfusOnWoW** [comment]
There's not enough benefit for the cost of implementing it.

**Comment by yankikucuk** [comment]
Alright. At least this conversation is on the record.

Have a nice week.

**Comment by mrbuds** [comment]
our proposed solution:
- action by user is copy/paste one file
- all user changes made are kept

your proposed solution
- action by user is
-- export all url
-- download every url from wago one by one
- all settings / changes made by user are lost

> If there are updated aura versions, no further action is required as it will pull the data from wago during import
weakauras companion or wago companion automate that already

**Comment by yankikucuk** [comment]
my proposed solution:

- action by user is export data.

>   -- download every url from wago one by one

this is not user action. this is application action.

> - all settings / changes made by user are lost

yes. this is true. but i was said:

> An idea where the two methods can be used together can also be considered.

lastly,

> weakauras companion or wago companion automate that already

and yes, with extra effort.

perhaps a portable version of the application could also be considered. Anyway.

The idea behind my ideas was actually to be able to do the same operation with much less effort for both the application and the users. not more.

however, you must have bigger issues on your mind, since major changes are needed to the current code, and rollup will be used instead of webpack.

**Comment by mrbuds** [comment]
> this is not user action. this is application action

This is out of scope of this application, it's not meant to copy a file from one computer to an other, there are enough apps made for the purpose of syncing files between computers

This ticket is duplicate of https://github.com/WeakAuras/WeakAuras-Companion/issues/852
