### ISSUE TITLE
MacOS app

### ISSUE THREAD

**Issue by 1stconsortium** [WeakAuras/WeakAuras-Companion#1968]
Got as far as it saying to finish setup. When I click on the gear to add the wow folder, I get the color spinning wheel and the app goes non responsive. After a time it stops but the same result each and every time, Is there another trick to add the wow folder, I have done all system updates 12/6/7/ Weekaruas is up to date. The companion app is up to date 5.0.1. Please help. Thank you.

**Comment by 1stconsortium** [comment]
How did this get closed with no resolution? Or is there no resolution?

**Comment by Stanzilla** [comment]
It should be fixed, have you tried with a recent version?
