### ISSUE TITLE
Update WeakAuras Addon Automagically

### ISSUE THREAD

**Issue by emptyrivers** [WeakAuras/WeakAuras-Companion#202]
Getting users to update their WeakAuras addon is a pain, sometimes. Could we offload some of that pressure onto the companion app, for at least the portion of our userbase which uses the app? The app could have settings for preferred release type, similar to the twitch app.

I'm not sure what else to say here, as this is not a project I've worked on much.

**Comment by Stanzilla** [comment]
I'd rather leave that to Twitch

**Comment by Stanzilla** [comment]
But notifications would probably be nice

**Comment by Stanzilla** [comment]
Twitch app has url handler that is currently broken (oh what a surprise) but we could launch the app to our addon with something like twitch://app/{id}
