### ISSUE TITLE
Receiving empty brackets when trying to add to companion app from website

### ISSUE THREAD

**Issue by Dillonzer** [WeakAuras/WeakAuras-Companion#2029]
**Operating System:**
- [x] Windows
- [ ] Mac
- [ ] Linux

**Companion Version:**
```
5.1.0
```

**Companion App Console Log:**
```
{}
```

**WeakAuras Version:**
```
5.7.0
```

**WeakAuras Errors:**
```
None
```

**Describe the bug**

**To Reproduce**
1. Go to https://wago.io/Gxpai4niQ
2. Click Send to Desktop App
3. Does not send to Desktop App

**Expected behavior**
It sends to Desktop App

**Screenshots**

**Include a .zip file containing:**
This is just my companion app config
[config.zip](https://github.com/WeakAuras/WeakAuras-Companion/files/12356009/config.zip)

**Comment by mrbuds** [comment]
This is solve in 5.1.1, ty for the report!
