### ISSUE TITLE
Companion shows WAs that have been deleted ingame

### ISSUE THREAD

**Issue by cremor** [WeakAuras/WeakAuras-Companion#2152]
**Operating System:**
- [x] Windows
- [ ] Mac
- [ ] Linux

**Companion Version:**
```
5.1.2
```

**Companion App Console Log:**
```
index-e51aa852.js:6 userDataPath C:\Users\Manuel\AppData\Roaming\weakauras-companion
5[Intervention] Slow network is detected. See <URL> for more details. Fallback font will be used while loading: <URL>
index-e51aa852.js:74 buildAccountList
index-e51aa852.js:95 validateWowPath
index-e51aa852.js:95 buildVersionList
index-e51aa852.js:74 buildAccountList
index-e51aa852.js:20 Plater not found at C:\Spiele\World of Warcraft\_retail_\Interface\AddOns
index-e51aa852.js:96 Creating default directory
index-e51aa852.js:96 promisesWagoCallsComplete
index-e51aa852.js:96 promisesWagoDataCallsComplete
index-e51aa852.js:20 writeAddonData
index-e51aa852.js:40 WeakAuras.toc has version: 100107
index-e51aa852.js:19 Backup: WeakAuras-_retail_#CREMOR01369-20231103143116.zip saved
index-e51aa852.js:96 promisesWagoCallsComplete
index-e51aa852.js:96 promisesWagoDataCallsComplete
index-e51aa852.js:20 writeAddonData
index-e51aa852.js:40 WeakAuras.toc has version: 100107
index-e51aa852.js:96 promisesWagoCallsComplete
index-e51aa852.js:96 promisesWagoDataCallsComplete
index-e51aa852.js:20 writeAddonData
index-e51aa852.js:40 WeakAuras.toc has version: 100107

```

**WeakAuras Version:**
```
5.8.3
```

**WeakAuras Errors:**
```
None
```

**Describe the bug**
The companion app still shows Weak Auras that have been deleted ingame.

**To Reproduce**
1. Import a Weak Aura ingame.
2. Close the game.
3. Check the companion app. The new Weak Aura is listed.
4. Delete the Weak Aura ingame.
5. Close the game.
6. Check the companion app. The Weak Aura is still listed.

**Expected behavior**
Deleted Weak Auras should be removed from the list in the companion.

**Include a .zip file containing:**
[Config.zip](https://github.com/WeakAuras/WeakAuras-Companion/files/13250740/Config.zip)

**Comment by mrbuds** [comment]
It's not possible to investigate without a copy of your weakauras data

**Comment by cremor** [comment]
I've attached it as was requested by the issue template. See linked zip file at the end of the post. Or do you need anything else?

**Comment by mrbuds** [comment]
Indeed both are in the file sorry, thanks

**Comment by mrbuds** [comment]
If you press the red button in settings and restart it should fix it for you, but that's still a bug that needs to be addressed

**Comment by mrbuds** [comment]
I should have asked which aura are you talking about, you don't say

**Comment by mrbuds** [comment]
i'll re-open if you can tell which aura are you talking about, i can't find them

**Comment by cremor** [comment]
I can't remember any more. But here are my current files: [Config.zip](https://github.com/WeakAuras/WeakAuras-Companion/files/13466219/Config.zip)
In those files the following two auras have already been deleted ingame:
https://wago.io/Zs6k2dJOt
https://wago.io/PaladinTalentReminders
