### ISSUE TITLE
Cannot run 5.12 on Ubuntu 23.10

### ISSUE THREAD

**Issue by rakkarage** [WeakAuras/WeakAuras-Companion#2180]
`Ubuntu 23.10 23.10 - Wayland - Vulkan (Forward+) - dedicated AMD Radeon RX 6600 (RADV NAVI23) () - 12th Gen Intel(R) Core(TM) i5-12400F (12 Threads)`

I am trying to install the companion app on linux...
First installed the deb but just shows empty window...
Tried download AppImage but same thing... empty window an errors:

	./WeakAuras-Companion-5.1.2.AppImage 
	11:08:19.091 › App starting...
	[22223:1119/110822.224033:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
	[22223:1119/110838.727641:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!

It works for a couple seconds... I can see window at first, can even click setup button if fast but still changes to all invis?

EDIT: 5.11 works.

Thanks.

**Comment by Stanzilla** [comment]
Looks like an upstream issue with Electron https://github.com/electron/electron/issues/32760
