### ISSUE TITLE
[Feature Request] drop shadow / glow on main window

### ISSUE THREAD

**Issue by Stanzilla** [WeakAuras/WeakAuras-Companion#224]
Currently our window is just very dark and has no borders, we should investigate a way how it can stand out a bit more on a dark background, maybe a drop shadow or glow around the main window

**Comment by mrbuds** [comment]
The shadow option works only on mac https://electronjs.org/docs/api/browser-window

**Comment by mrbuds** [comment]
Discord has a slight shadow, i don't know how they do it but i can ask somewhere, is that what you want ?

**Comment by Stanzilla** [comment]
Yeah pretty much, I already tried to add it myself but like you said, haven't found a good way on Windows
