### ISSUE TITLE
no updateable auras installed on this account after updating companion to 5.1.3

### ISSUE THREAD

**Issue by sindaliza** [WeakAuras/WeakAuras-Companion#2250]
campanion broke after i updated it to 5.1.3....have uninstalled and reinstalled both the companion and the weakauras ingame and it still just states that i have no updateable auras installed but it worked fine prior to the update.  all my weakauras are from the wago.io site. 
![2023-12-19 (1)](https://github.com/WeakAuras/WeakAuras-Companion/assets/41693853/11256d67-9d21-46a2-ac66-7598f9be087b)
![2023-12-19 (2)](https://github.com/WeakAuras/WeakAuras-Companion/assets/41693853/16891022-d0c2-4a8b-b6ef-66036ce22952)
![2023-12-19 (3)](https://github.com/WeakAuras/WeakAuras-Companion/assets/41693853/3e35a2be-dd2f-4a42-8f90-a71fc1d7911f)

**Comment by cremor** [comment]
I also sometimes get this message since about one or two weeks ago. For me it was not directly related to the 5.1.3 update. That worked fine for some time. So maybe it's a server side problem?

Anyways, for me there is a simple fix: Restarting the companion app finds the auras again.

**Comment by tomrus88** [comment]
Getting this problem randomly as well. Selecting account from dropdown usually makes it go away...

**Comment by Stanzilla** [comment]
This should be better in 5.2.1
