### ISSUE TITLE
Version 1.1.9 don't start on a fresh Pop!_Os 19.04 (Ubuntu 19.04) Installation

### ISSUE THREAD

**Issue by cataldoc** [WeakAuras/WeakAuras-Companion#233]
Hi

On a fresh OS installation, I installed weakauras-companion snap with the following command:

`sudo snap install --dangerous ./weakauras-companion_1.1.9_amd64.snap`

But if I try to run it, it doesn't start and this is the error I get:

```
$ snap run weakauras-companion
[8461:0517/194801.338604:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /snap/weakauras-companion/x1/chrome-sandbox is owned by root and has mode 4755.
Rilevato trace/breakpoint (core dumped)
```

I have no issues with other snaps (eg. Discord is running fine)

**Comment by emptyrivers** [comment]
Well, did you make sure that the sandbox is owned by root and has mode 4755?

**Comment by cataldoc** [comment]
Hi, sorry I should have mentioned it... the file is owned by root but permissions are 0755 instead of 4755
The problem is that the snap filesystem is readonly and I can't change it

**Comment by Stanzilla** [comment]
Not quite sure if this is something we can/have to fix?

**Comment by cataldoc** [comment]
well, It's impossible to change the contents of the snap without re-building the snap. So I guess the only way to fix it is to change the permissions and rebuild it

**Comment by cataldoc** [comment]
https://askubuntu.com/questions/919091/why-can-snap-files-not-be-modified-in-any-way

**Comment by Stanzilla** [comment]
@cataldoc any idea on what we are doing wrong then? and where we do it wrong?

**Comment by cataldoc** [comment]
I'm not really an expert with snap, but I've found this topic which describe a possible workaround: https://forum.snapcraft.io/t/call-for-testing-chromium-snap/1714/15

> use snapcraft build the snap
> unsquash the snap
> chown root:root …/chrome-sandbox
> chmod 4755 …/chrome-sandbox
> snapcraft snap ./squashfs-root

Not sure this can work tho...

**Comment by cataldoc** [comment]
I have found a workarund... the issue seems to be related to apparmor security profiles ( https://docs.ubuntu.com/core/en/guides/intro/security )

There's currently a way to install a snap disabling all security checks by installing it using the devmode flag

`sudo snap install --devmode <snap>`

this way weakauras-companion works (even tho no security is enforced)
