### ISSUE TITLE
[Feature Request] Load Aura when certain buff is/is not applied

### ISSUE THREAD

**Issue by Madsvittrup** [WeakAuras/WeakAuras-Companion#2413]
I have an aura that I want to unload (reset the timers and CDs) during arena preperation, since solo shuffle continues and doesn't leave the arena between each game. The delay timer will continue and show the aura next round..

Currently the system I had to make is unequipping a staff to unload the aura between rounds. Is there a way to make this a more simple affair? Perhaps if I could unload under different circumstances it'd be perfect. 

If this isn't possible that's understandable. Thx for your time!

**Comment by InfusOnWoW** [comment]
Load Options on a buff being applied is not a good idea.
