### ISSUE TITLE
Huge Menu Bar Extra on Mac OSX

### ISSUE THREAD

**Issue by bsolar17** [WeakAuras/WeakAuras-Companion#252]
On Mac OSX the app creates a huge Menu Bar Extra on the menu bar:

![image](https://user-images.githubusercontent.com/7414158/58745742-09063880-8455-11e9-9c8b-6a50382ccf14.png)

The Menu Bar Extra is far too large: I guess the icon is not appropriately scaled according to the menu size.

Furthermore, I found no way to disable it. According to the [Apple Human Interface Guidelines](https://developer.apple.com/design/human-interface-guidelines/macos/extensions/menu-bar-extras/) Menu Bar Extras should be optional.

I tried both app versions 1.1.12 and 1.2.0-beta4 on macOS Mojave 10.14.5.

**Comment by Scabbrox** [comment]
Yep, came to say the same. Last two updates have this issue, previous ones did not.

**Comment by Stanzilla** [comment]
Should be fixed with the release from today, can you guys confirm?

**Comment by Scabbrox** [comment]
Yep, thanks back to normal size.
