### ISSUE TITLE
Please select wow version.. no place to select 

### ISSUE THREAD

**Issue by b1n4ryk1lla** [WeakAuras/WeakAuras-Companion#253]
**Operating System:**
- [x ] Windows
- [ ] Mac
- [ ] Linux

**Companion Version:**
1.2.0 beta v4

**Describe the bug**
says please select your wow version but the option in settings is not there anymore
**To Reproduce**
start app ??? 
**Expected behavior**
check for updates to weak aura 
**Screenshots**
https://imgur.com/a/V6ItFuq
**Include a .zip file containing:**
N/A

**Comment by b1n4ryk1lla** [comment]
1.1.12 

also is not showing any settings at all just a blank page and main tab is unresponsive 

https://imgur.com/a/VrJBSEF

**Comment by mrbuds** [comment]
Thanks for the report
Can you open the console (Ctrl+Shift+I => console tab) and copy errors here ?
Also can you give your %APPDATA/weakauras-companion/config.json ?

**Comment by mrbuds** [comment]
@b1n4ryk1lla i can't fix your issue without an answer.

PS: Pushing the red reset button should fix it, but this will not help me to solve the problem for everyone, i can't release 1.2.0 with this bug.

**Comment by mrbuds** [comment]
should be fixed on current release
