### ISSUE TITLE
[Feature] Allow Minimizing To System Try On Close 

### ISSUE THREAD

**Issue by zwang180** [WeakAuras/WeakAuras-Companion#2530]
Hi there,

Great app! I'm a Windows user and it'd be nice if you could add a setting to change the behavior of the close button (i.e. the `x` button) from "closing the app completely" to "minimize it to system try but keeping it running in the background".

Many thanks!

**Comment by Starlynk1** [comment]
It minimizes to System Tray on minimize. I agree an option to minimize on close would be nice to have, but also defeats the purpose of closing an app if it stays open.
