### ISSUE TITLE
comagnion app  always blurry

### ISSUE THREAD

**Issue by Kraystase** [WeakAuras/WeakAuras-Companion#2559]
Hello 
Just compagnion app always Blurry 

addon is ok  , aura is ok, just  software  bug blurry

in 2560x1440  (2k) 144hz

**Operating System:**
- [ ] Windows 11 64bit

All drivers is up to date 

**Companion Version:**  5.2.4 

can you do something ?

thanks for all 

Kraystase

![WA companion](https://github.com/user-attachments/assets/e7cd661e-f8fc-4457-9fb1-405561bb8c31)

**Comment by mrbuds** [comment]
I think the problem is caused by gpu acceleration and the anti-aliasing settings as mention on this page https://answers.microsoft.com/en-us/windows/forum/all/blurry-apps-in-windows-1011-a-workaround/e7538b47-eba0-45e0-88f7-7e011b0cb9a4

**Comment by Kraystase** [comment]
ho ok , thanks  i do it ^^ 
sorry for take your time for this bug

**Comment by mrbuds** [comment]
No worries, i encountered this issue myself when i played with nvidia global anti aliasing settings
