### ISSUE TITLE
5.2.5 doesnt work

### ISSUE THREAD

**Issue by razgriz5000** [WeakAuras/WeakAuras-Companion#2574]
windows 11, clean install of 5.2.5. nothing loads and nothing is clickable.  see picture below

![image](https://github.com/user-attachments/assets/cd2f06e2-f006-4447-aace-47e0fed5f755)

**Comment by mrbuds** [comment]
Thanks for the report we are investigating

**Comment by evangarstorm** [comment]
i have the same issue with 5.2.5.. Windows 11 (with latest "amd" update KB5041587).

**Comment by nerf10** [comment]
same for me

**Comment by Isilrond** [comment]
same here

**Comment by mrbuds** [comment]
5.2.6 was published and fix this problem
