### ISSUE TITLE
Update button on client doesn't work - instead displays null

### ISSUE THREAD

**Issue by navara** [WeakAuras/WeakAuras-Companion#2596]
Hover over the button returns: "install client update: vnull null"

Windows 10
Companion 5.2.4
No new console items on hover/click on the button

![image](https://github.com/user-attachments/assets/5d90f7c7-dc18-4ebb-8fa5-131cbe2f2ed3)

**Comment by GhostReapersWorld** [comment]
Can confirm, I have the same bug.
