### ISSUE TITLE
Window keeps growing when moving around / resizing

### ISSUE THREAD

**Issue by avilene** [WeakAuras/WeakAuras-Companion#283]
**Operating System:**
- [x] Windows
- [ ] Mac
- [ ] Linux

**Companion Version:** 1.2.1

**Companion App Console Log:**
```
renderer.js:1 validateWowpath
renderer.js:1 buildAccountList
renderer.js:1 buildVersionList
renderer.js:1 buildAccountList
renderer.js:1 Backup: weakauras-_retail_#106424544#1-20190621230737.zip saved
renderer.js:1 updaterHandler: update-not-available
renderer.js:1 updaterHandler: checkForUpdates
```

**WeakAuras Version:** 2.12.4.2

**Describe the bug**
Whenever I interact with the window by moving it, it grows bigger and bigger. This results in a window that is too big to fit on the screen

**To Reproduce**
1. Open the application
2. Move the window around
3. Observe constant resizing.

**Expected behavior**
The window should not grow bigger whenever it is being moved around.

**Include a .zip file containing:**
[WeakAuras-Companion.zip](https://github.com/WeakAuras/WeakAuras-Companion/files/3316062/WeakAuras-Companion.zip)

**Comment by Stanzilla** [comment]
Is still stil happening?

**Comment by avilene** [comment]
Yes, this is still happening for me.
