### ISSUE TITLE
Companion does not display the installed version of a weakaure

### ISSUE THREAD

**Issue by Moowalker** [WeakAuras/WeakAuras-Companion#40]
According to this weakaura the version should be 2.0.6-26
![image](https://user-images.githubusercontent.com/14836857/50522837-a68bc380-0ad5-11e9-91b9-efb3e3f821e9.png)

but companion app displays v26 as the installed weakaura
![image](https://user-images.githubusercontent.com/14836857/50522869-c622ec00-0ad5-11e9-8b94-b3a90a7d9b87.png)

instead of v26 (the old versioning system of wago) it should display 2.0.6-26 (the new versioning system).

Running dev from commit: d9d09c2fb1580eef0e20d364239b37d5c4fe4bc6

**Comment by mrbuds** [comment]
fixed with #c8c077ab575b63613a230a0968d9ffbec09d143b
