### ISSUE TITLE
[Webpack] Process is not defined

### ISSUE THREAD

**Issue by kendinikertenkelebek** [WeakAuras/WeakAuras-Companion#408]
**Operating System:**
- [ ] Windows
- [x] Mac
- [ ] Linux

**Companion Version:**
```
master branch
```

**Companion App Console Log:**

[Webpack reference error - Issue#871](https://github.com/SimulatedGREG/electron-vue/issues/871)

**Describe the bug**
when type in terminal ("npm run dev")

**To Reproduce**
1. Clone master branch on your desktop
2. install dependencies
3. run command in terminal: `npm run dev`

**Expected behavior**
WeakAuras Companion main window.

**Screenshots**
Same screenshot like at link (above)

**Comment by Stanzilla** [comment]
Are you on node@12? Does it work if you switch to node@10?

**Comment by kendinikertenkelebek** [comment]
Didn't find any issue with node@10.16. It only happens on node@12.10.

I found a solution like this:

go to .electron-vue folder and open `webpack.renderer.config.js` so, add this code after line 134

```js
templateParameters(compilation, assets, options) {
        return {
          compilation: compilation,
          webpack: compilation.getStats().toJson(),
          webpackConfig: compilation.options,
          htmlWebpackPlugin: {
            files: assets,
            options: options
          },
          process,
        };
      },
```

It works well for me. But this is a temporary solution. Maybe added to the master branch. Who knows?

**Comment by Stanzilla** [comment]
The problem is that electron-vue is pretty dead but I already added that workaround, will commit now
