### ISSUE TITLE
[Future Request] Add to addOn Button

### ISSUE THREAD

**Issue by kendinikertenkelebek** [WeakAuras/WeakAuras-Companion#417]
Why we're using copy-paste for these strings in 2019 Q4?

1. Can we put a button like "add to addon" on wago and wago automatically send our desktop app using with user API key?
2. And then just simply reload UI in-game.
3. Profit.

**Comment by InfusOnWoW** [comment]
Duplicate of https://github.com/WeakAuras/WeakAuras-Companion/issues/44
