### ISSUE TITLE
Changes to UI/UX 

### ISSUE THREAD

**Issue by ql1max** [WeakAuras/WeakAuras-Companion#43]
I've made some UI/UX fixes, mostly sizes and aligning stuff to the grid, also worked the colors a little so we don't have so many variations of black and grey across the whole app; I know It's not perfect (i'm kinda limited in time at the moment). I can help/do more on it later. You can see what i worked on in the folowing link:
https://www.figma.com/file/NFlj2Hfl0qf7VMvGjx72rDXq/wa-companion?node-id=0%3A1

**Comment by mrbuds** [comment]
The fetch updates icon looks like it is for reverting changes rather than updating

**Comment by ql1max** [comment]
@mrbuds Yeah, you're right. Easy to fix though, we can add a second arrow going the other way creating a more obvious update icon

**Comment by mrbuds** [comment]
from @sragia on discord

> I actually implemented quite a bit of it but still a bit of work with paddings/sizes for header and footer.

 
![](https://i.imgur.com/R6axael.gif)



My first thoughts on that 

Black text hover white background for both "fetch updates" button and notification feels off with the rest of the design to me

![](https://i.imgur.com/LgKyDrw.png)
![](https://i.imgur.com/1usWwEr.png)

Previous design was easier to read, mixing vertical, horizontal and diagonal lines with text makes my eyes bleed

I really like the top bar and how the fetch button move to top.

**Comment by Stanzilla** [comment]
First part is merged, https://github.com/WeakAuras/WeakAuras-Companion/pull/47

Time to iterate more! So far the only tab I don't like the look of is the `About` one, not sure what to do about it yet though.

**Comment by mrbuds** [comment]
![hover](https://i.imgur.com/XaY5Dk3.gif)

**Comment by Stanzilla** [comment]
The green on the settings page should probably the same green as the wow logo in the toast?

**Comment by mrbuds** [comment]
I know v-tooltip has close to zero flexibility but i wished tooltips follow cursor like this ![tooltip](https://i.imgur.com/Wu367ws.gif)

**Comment by Nightwarden24** [comment]
Toast message has a small space on the right. The same should be done on the left. Do you agree?

![](https://i.imgur.com/6eZWFRl.png)

**Comment by Vardex** [comment]
On the settings can you align _Reset Settings and Data_ to the rest of the settings like this?:
![image](https://user-images.githubusercontent.com/12969608/50931399-bf479200-1462-11e9-9650-2d8bdd57d033.png)

Also, I like it without the WA logo in the background.

**Comment by Nightwarden24** [comment]
if you click 'found a bug', there is WA logo in the background. LoL

**Comment by mrbuds** [comment]
Issues brought up by Asakawa on Discord:
- Draggable aeras on top don't let you resize window
- Can't drag window by clicking on menu buttons
- Dead aera on top right
