### ISSUE TITLE
Window growing when trying to move

### ISSUE THREAD

**Issue by zerbiniandrea** [WeakAuras/WeakAuras-Companion#463]
**Operating System:**
- [x] Windows
- [ ] Mac
- [ ] Linux

**Companion Version:**
```
1.2.4
```

**Companion App Console Log:**
```
validateWowpath
renderer.js:7 buildAccountList
renderer.js:7 buildVersionList
renderer.js:7 buildAccountList
renderer.js:7 updaterHandler: update-not-available
renderer.js:7 updaterHandler: checkForUpdates
```

**WeakAuras Version:**
```
2.15.5
```

**Describe the bug**
When I try to move the Window around the screen, it keeps growing bigger. It happens when I click on the "title bar" (where there's Main, Settings, About and Help).

**To Reproduce**
1. Open the app
2. Move the app/Click on the title bar and keep pressed
3. The window keeps getting bigger

**Expected behavior**
The window should not grow until it's bigger than the screen

**Include a .zip file containing:**
`%programfiles%\World of Warcraft\_retail_\WTF\Account\<AccountName>\SavedVariables\WeakAuras.lua`
AND
`%appdata%\weakauras-companion\config.json`

[WeakAuras.zip](https://github.com/WeakAuras/WeakAuras-Companion/files/3827685/WeakAuras.zip)

**Comment by Stanzilla** [comment]
Hey Andrea, thanks for the report. We changed a lot of window handling code recently and are pretty sure that was finally fixed. Could you please try one of our test builds to confirm? 

https://github.com/WeakAuras/WeakAuras-Companion/suites/300752830/artifacts/268968

**Comment by zerbiniandrea** [comment]
Yes, that build works fine! I've tried to move/resize the window and it looks like it isn't bugged.

**Comment by mrbuds** [comment]
You can switch to the beta channel to try 2.0.0-beta1 that fix this issue.
