### ISSUE TITLE
Dragging the Companion Window causes mouse to stick and window to resize itself indefinitely

### ISSUE THREAD

**Issue by panoplybez** [WeakAuras/WeakAuras-Companion#475]
**Operating System:**
Windows 10 Home

**Companion Version:**
1.2.4

**Describe the bug**
After opening the app, if you click in the top section as if to drag the app around on the screen, it causes the mouse to stick, and then causes the window to resize itself larger and larger. This keeps happening every time you move the mouse, until you hit ESC.

**To Reproduce**
1. Open Companion App on Windows Desktop
2. Click the top section where it says WA Companion
3. Try to drag the window around on the screen and watch it get larger/mouse get locked.
4. Hit Esc to unlock the mouse.

**Expected behavior**
Window should not resize itself, Mouse should not get locked, Window should be drag-gable around the screen at its normal size.

**Comment by panoplybez** [comment]
Just noticed this was addressed in an earlier ticket! Will await the test build.

**Comment by mrbuds** [comment]
You can switch to the beta channel to try 2.0.0-beta1 that fix this issue.

**Comment by panoplybez** [comment]
Thanks!
