### ISSUE TITLE
can't select the wow folder

### ISSUE THREAD

**Issue by OneOfOne** [WeakAuras/WeakAuras-Companion#488]
**Operating System:**
- [X] Windows (wine)
- [ ] Mac
- [X] Linux (appimage)

**Companion Version:** 2.0.0-beta1 and 1.2.4 both the "windows" version on wine and linux version

**Companion App Console Log:**
Can't, getting:
```
./WeakAuras-Companion-2.0.0-beta1.appimage --help
11:03:56.819 › App starting...
11:03:57.387 › Checking for update
(node:75502) ProtocolDeprecateCallback: The callback argument of protocol module APIs is no longer needed.
(node:75502) ProtocolDeprecateCallback: The callback argument of protocol module APIs is no longer needed.
11:03:58.215 › Update for version 2.0.0-beta1 is not available (latest version: 2.0.0-beta1, downgrade is allowed).

(weakauras-companion:75502): Gtk-WARNING **: 11:04:03.259: Failed to measure available space: The specified location is not supported
[75502:1130/110437.469357:ERROR:CONSOLE(7278)] "Uncaught TypeError: Cannot read property 'indexOf' of undefined", source: devtools://devtools/bundled/shell.js (7278)
[75502:1130/110449.955198:ERROR:CONSOLE(7278)] "Uncaught TypeError: Cannot read property 'indexOf' of undefined", source: devtools://devtools/bundled/shell.js (7278)
```

**Describe the bug**

The main window shows "Finish Setup", which takes you to settings, trying to select the wow folder doesn't do anything.

Tried:
* /games/World\ of\ Warcraft/_retail_
* /games/World\ of\ Warcraft/_retail_/Interface
* /games/World\ of\ Warcraft/

I know it's not my setup because Curse, wowman and raider.io works fine.

**Comment by s19locke** [comment]
Did you get this fixed? Im basicly seeing the same issue and clueless

**Comment by mrbuds** [comment]
Please make a new ticket if you have an issue

**Comment by s19locke** [comment]
Apologies its seems remarkable similar to the issue  i have already listed in https://github.com/WeakAuras/WeakAuras-Companion/issues/506, he closed it himself so it sounds like its fixed but nothing was listed as to what fixed it. Again sorry was just hoping for a fix

**Comment by mrbuds** [comment]
Please make a new ticket if you have an issue

**Comment by mrbuds** [comment]
A fix for this issue was implemented in the last beta version, you can get it by checking this option in the "Settings" tab
![img](https://i.imgur.com/aSCrvZb.png)

**Comment by Galiwyx** [comment]
I have the same error. But I can't download the Beta version : 

![image](https://user-images.githubusercontent.com/206181/71534252-c4b11d00-28fd-11ea-9220-7b23d4b57c70.png)

**Comment by mrbuds** [comment]
Updater in 2.0.0 is not working (known issue).
You can get beta version from https://github.com/WeakAuras/WeakAuras-Companion/releases

**Comment by Galiwyx** [comment]
Thank you !!
