### ISSUE TITLE
WA Companion Mac is not allowing me to select my wow folder.

### ISSUE THREAD

**Issue by tmedley** [WeakAuras/WeakAuras-Companion#507]
I am running into an issue with the app, it will not see my WoW folder, the icon stays red.

I am a Mac user running 10.14.6 and WA Companion 2.0.0. In Settings, I am clicking the folder icon then selecting my World of Warcraft Folder which is under /Applications/World of Warcraft/   I even tried selecting the retail folder and the WTF under retail, but nothing works. I have clicked the red button to reset the settings, rebooted a few times and reinstalled the WA Companion app.

I am running WeakAuras 2.15.5 retail and it's working in game just fine. I have verified that my WeakAuras.lua file is there under World of Warcraft/_retail_/WTF/Account/<AccountName>/SavedVariables

Vardex was trying to assist me on Discord but wasn't sure how else to proceed. Attaching the screenshot from the Chromium console and from the mac console.app.

<img width="1290" alt="Screen Shot 2019-12-12 at 3 31 45 PM" src="https://user-images.githubusercontent.com/14044285/70757511-e01d0500-1d0d-11ea-9cf3-5c88db36fd2f.png">
<img width="803" alt="Screen Shot 2019-12-12 at 3 37 57 PM" src="https://user-images.githubusercontent.com/14044285/70757512-e01d0500-1d0d-11ea-810d-6ca17f1aae14.png">

**Comment by Slahser** [comment]
me too. subscribed this issue.

**Comment by mrbuds** [comment]
I can't reproduce the issue and i don't have a fix yet, but as a workaround you can try replacing `%appdata%/weakauras-companion/config.json` with this file https://cdn.discordapp.com/attachments/532314347477925891/658477597205856278/config_-_Copy.zip rename it, and edit the path of you wow folder

**Comment by mrbuds** [comment]
A fix for this issue was implemented in the last beta version, you can get it by checking this option in the "Settings" tab
![img](https://i.imgur.com/aSCrvZb.png)

**Comment by HappyCan303** [comment]
I'm seeing a beta release 2.0.1 in the Companion Beta channel notification but when I go to download and install I'm taken to the 2.0.0 GitHub page. Can you point me to the 2.0.1 beta1 install?

If I'm just missing something obvious, I apologize.

**Comment by mrbuds** [comment]
Restart the app when it's downloaded and it should auto install it

**Comment by tmedley** [comment]
I am having the same issue. At the bottom of the WA companion app window, it shows "Companion Update Available". If I hover over the download button in the bottom right corner, it says, "Install client update v2.0.1-beta1". If I click the download button, it takes me to the Github page for 2.0.0 release:  https://github.com/WeakAuras/WeakAuras-Companion/releases/tag/v2.0.0

In settings, I have "Use Companion Beta channel" enabled. I have tried both enabling and disabling "Install Companion updates automatically"

I have Reset Settings and Data, reinstalled the Companion app and rebooted several times with the same results.

Can someone please provide a direct link to the 2.0.1-beta1 app?

**Comment by mrbuds** [comment]
You can get latest beta at https://github.com/WeakAuras/WeakAuras-Companion/releases
Next update will link to this instead of the latest release

**Comment by tmedley** [comment]
That worked, thank you. I was able to install the new beta and it lets me choose my wow folder correctly. I am good to go.

**Comment by TwilightDevastation** [comment]
How was this broken app released for Mac in the first place? It either doesn't work completely (the only way to open the window is using Terminal), or when you do, its the exact same problem described above: 
![Screenshot 2020-01-25 at 17 17 53](https://user-images.githubusercontent.com/60295634/73124044-d6d2b980-3f96-11ea-96fc-a619f9ec6fcb.png)

**Comment by Stanzilla** [comment]
It works just fine on my mac
