### ISSUE TITLE
No application window on macOS

### ISSUE THREAD

**Issue by GaryREM** [WeakAuras/WeakAuras-Companion#538]
Both 2.0 and beta start up but I get no windows displayed.

Can get the About window to display.

macOS 10.15.2

Note that I see main program, and 3 helpers in activity monitor.

**Comment by GaryREM** [comment]
OK. This is a UI issue apparently.

If you start the companion app, it runs but presents no windows. If you then go to the WA icon in the menu bar, you can open the companion window.

I would think that when you initially start the program the window should, by default, display.

**Comment by Vardex** [comment]
Have you tried unchecking `Start client minimized` in the Settings tab?

**Comment by GaryREM** [comment]
OK, yes! So that explains it. 

Since I didn’t see a preferences/settings option in the weakauras menus, I was stuck until I realized the menu item was there.

It would be nice to have a preferences/settings item in the weakauras main menu if possible.

Thanks for the explanation. 

Gary
