### ISSUE TITLE
Weakauras in game dont update

### ISSUE THREAD

**Issue by Jcblmao** [WeakAuras/WeakAuras-Companion#564]
when updating in game after "updating" from the companion app, always get errors.

[12:11] [Error 000001AA05C29010] captured, click the link for more information. 
[12:11] [Error 000001AA05C29010] captured, click the link for more information. 
[12:11] Interface\AddOns\WeakAuras\Transmission.lua:1238: attempt to get length of field 'controlledChildren' (a nil value) 
[12:11] [string "@Interface\AddOns\WeakAuras\Transmission.lua"]:1238: in function `MatchInfo'
[string "@Interface\AddOns\WeakAuras\Transmission.lua"]:1776: in function `Import'
[string "@Interface\AddOns\WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua"]:781: in function <...eGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua:778> 
[12:11] data = <table> {
 grow = "RIGHT"
 controlledChildren = <table> {
 }
 borderBackdrop = false
 xOffset = -451.999878
 yOffset = 208.000854
 gridType = "RD"
 borderColor = <table> {
 }
 rowSpace = 1
 actions = <table> {
 }
 triggers = <table> {
 }
 columnSpace = 1
 internalVersion = 26
 selfPoint = "LEFT"
 align = "CENTER"
 stagger = 0
 version = 68
 animation = <table> {
 }
 load = <table> {
 }
 borderInset = 0
 backdropColor = <table> {
 }
 borderSize = 2
 animate = false
 rotation = 0
 scale = 1
 space = 2
 border = false
 borderEdge = false
 regionType = "dynamicgroup"
 hybridPosition = "hybridFirst"
 limit = 5
 config = <table> {
 }
 radius = 200
 hybridSortMode = "ascending"
 constantFactor = "RADIUS"
 gridWidth = 5
 borderOffset = 16
 semver = "24.0.0"
 arcLength = 360
 id = "Eternal Palace Auras - Reloe"
 anchorPoint = "CENTER"
 frameStrata = 1
 anchorFrameType = "SCREEN"
 authorOptions = <table> {
 }
 uid = "PcXbSTFrvVF"
 sort = "hybrid"
 url = "https://wago.io/_xTUqKimJ/68"
 conditions = <table> {
 }
 sortHybridTable = <table> {
 }
 useLimit = false
}
children = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
 4 = <table> {
 }
 5 = <table> {
 }
 6 = <table> {
 }
 7 = <table> {
 }
 8 = <table> {
 }
 9 = <table> {
 }
 10 = <table> {
 }
 11 = <table> {
 }
 12 = <table> {
 }
 13 = <table> {
 }
 14 = <table> {
 }
 15 = <table> {
 }
 16 = <table> {
 }
 17 = <table> {
 }
 18 = <table> {
 }
 19 = <table> {
 }
 20 = <table> {
 }
 21 = <table> {
 }
 22 = <table> {
 }
 23 = <table> {
 }
 24 = <table> {
 }
 25 = <table> {
 }
 26 = <table> {
 }
 27 = <table> {
 }
 28 = <table> {
 }
 29 = <table> {
 }
 30 = <table> {
 }
 31 = <table> {
 }
 32 = <table> {
 }
 33 = <table> {
 }
 34 = <table> {
 }
 35 = <table> {
 }
 36 = <table> {
 }
 37 = <table> {
 }
 38 = <table> {
 }
 39 = <table> {
 }
 40 = <table> {
 }
 41 = <table> {
 }
 42 = <table> {
 }
 43 = <table> {
 }
 44 = <table> {
 }
 45 = <table> {
 }
 46 = <table> {
 }
 47 = <table> {
 }
 48 = <table> {
 }
 49 = <table> {
 }
 50 = <table> {
 }
 51 = <table> {
 }
 52 = <table> {
 }
 53 = <table> {
 }
 54 = <table> {
 }
 55 = <table> {
 }
 56 = <table> {
 }
 57 = <table> {
 }
 58 = <table> {
 }
 59 = <table> {
 }
 60 = <table> {
 }
 61 = <table> {
 }
 62 = <table> {
 }
 63 = <table> {
 }
 64 = <table> {
 }
 65 = <table> {
 }
 66 = <table> {
 }
 67 = <table> {
 }
 68 = <table> {
 }
 69 = <table> {
 }
 70 = <table> {
 }
 71 = <table> {
 }
 72 = <table> {
 }
 73 = <table> {
 }
 74 = <table> {
 }
 75 = <table> {
 }
 76 = <table> {
 }
 77 = <table> {
 }
 78 = <table> {
 }
 79 = <table> {
 }
 80 = <table> {
 }
 81 = <table> {
 }
 82 = <table> {
 }
 83 = <table> {
 }
 84 = <table> {
 }
 85 = <table> {
 }
 86 = <table> {
 }
 87 = <table> {
 }
 88 = <table> {
 }
 89 = <table> {
 }
 90 = <table> {
 }
 91 = <table> {
 }
 92 = <table> {
 }
 93 = <table> {
 }
 94 = <table> {
 }
 95 = <table> {
 }
 96 = <table> {
 }
 97 = <table> {
 }
 98 = <table> {
 }
 99 = <table> {
 }
 100 = <table> {
 }
 101 = <table> {
 }
 102 = <table> {
 }
 103 = <table> {
 }
 104 = <table> {
 }
 105 = <table> {
 }
 106 = <table> {
 }
 107 = <table> {
 }
 108 = <table> {
 }
 109 = <table> {
 }
 110 = <table> {
 }
 111 = <table> {
 }
 112 = <table> {
 }
 113 = <table> {
 }
 114 = <table> {
 }
 115 = <table> {
 }
 116 = <table> {
 }
 117 = <table> {
 }
 118 = <table> {
 }
 119 = <table> {
 }
 120 = <table> {
 }
 121 = <table> {
 }
 122 = <table> {
 }
 123 = <table> {
 }
}
target = <table> {
 xOffset = -295.741455
 customText = ""
 yOffset = 268.842041
 anchorPoint = "CENTER"
 cooldownSwipe = true
 customTextUpdate = "event"
 url = "https://wago.io/_xTUqKimJ/34"
 icon = true
 internalVersion = 26
 animation = <table> {
 }
 tocversion = 80205
 stickyDuration = false
 auto = true
 version = 34
 subRegions = <table> {
 }
 height = 42.372540
 actions = <table> {
 }
 selfPoint = "CENTER"
 color = <table> {
 }
 triggers = <table> {
 }
 keepAspectRatio = false
 load = <table> {
 }
 config = <table> {
 }
 regionType = "icon"
 authorOptions = <table> {
 }
 width = 47.392021
 frameStrata = 1
 desaturate = false
 sem

**Comment by InfusOnWoW** [comment]
You need to add a lot more info on how to reproduce. E.g. the actual aura that you are trying to update in game, a link to the wago url that you are trying to update from. Etc.

**Comment by mrbuds** [comment]
This is duplicate of https://github.com/WeakAuras/WeakAuras-Companion/issues/68
