### ISSUE TITLE
Companion trying to push already updated auras

### ISSUE THREAD

**Issue by Winney1907** [WeakAuras/WeakAuras-Companion#57]
**Operating System:**
- [x] Windows
- [ ] Mac
- [ ] Linux

**Companion Version:**
1.0.15

**WeakAuras Version:**
```
2.11.0-beta2-3-g3f844cf
```

**Describe the bug**
The companion app and ingame weakauras is displaying this weakaura: https://wago.io/4y7qKOBVW as being out of date even after importing the "updated" weakaura.

**Include a .zip file containing:**
[WA.zip](https://github.com/WeakAuras/WeakAuras-Companion/files/2746843/WA.zip)

**Comment by Winney1907** [comment]
Closed game files:
[WA2.zip](https://github.com/WeakAuras/WeakAuras-Companion/files/2747254/WA2.zip)

**Comment by mrbuds** [comment]
I can't reproduce https://www.twitch.tv/videos/361942544
If you click the red button "Reset Settings and Data" in the Settings panel, does it fix it?

**Comment by mrbuds** [comment]
> 00:36] Winni: reseting didnt fix it but i just completely removed the aura and reimported and its fine now
