### ISSUE TITLE
Consider dropping babel and core-js

### ISSUE THREAD

**Issue by Zireael-N** [WeakAuras/WeakAuras-Companion#608]
Since you control the environment, there's no reason to compile to an older version of ES and add polyfills.

On the contrary, it negatively impacts your build time and makes the compiled project's size larger than it needs to be.

Electron 8.1.0 is based on Chromium 80, even the [nullish coalescing operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator) and [optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) are available.

I can work on this if you are interested.

**Comment by Stanzilla** [comment]
Yup, I wanted to do that but would be super happy if you can do a PR!
