### ISSUE TITLE
Content doesn't fit

### ISSUE THREAD

**Issue by Nightwarden24** [WeakAuras/WeakAuras-Companion#64]
**Operating System:**
- [x] Windows
- [ ] Mac
- [ ] Linux

**Companion Version:**
```
1.0.18
```
**Describe the bug**
Content doesn't fit in the header and in a dropdown box of language with the minimum width of application window

**Screenshots**

![](https://i.imgur.com/xb8sO9Q.png)

![](https://i.imgur.com/xRxEfNv.png)

![](https://i.imgur.com/W0VfkSK.png)

**Comment by Stanzilla** [comment]
@Nightwarden24 is this still a problem?

**Comment by Nightwarden24** [comment]
As far as I remember, not anymore - issue has been solved
