### ISSUE TITLE
Prettier errors using dev or build scripts

### ISSUE THREAD

**Issue by marcelmfa** [WeakAuras/WeakAuras-Companion#648]
**Operating System:**
- [X] Windows
- [ ] Mac
- [ ] Linux

**Companion Version:**
Lastest

**Companion App Console Log:**
From GitBash client - https://gist.github.com/marcelmfa/da2529ca6a16cdab184ce25aca788a9a

**WeakAuras Version:**
Latest

**WeakAuras Errors:**
N/A

**Describe the bug**
I am getting prettier errors using dev and build scripts and cannot run app.

**To Reproduce**
1. Updated repo using git pull
2. Ran `yarn` command
3. Ran `yarn dev` or `yarn build` results in same errors

**Expected behavior**
Open app

**Screenshots**
N/A

**Comment by emptyrivers** [comment]
This was fixed previously in a pull request that was just merged.
