### ISSUE TITLE
[Feature Request] Sorting/Searching in the companion app

### ISSUE THREAD

**Issue by LootFeverTV** [WeakAuras/WeakAuras-Companion#658]
Lately I often get asked for a specific WA while I'm not ingame and start scrolling through the main window of the companion app.

It would be nice if we could sort the entries in there (alphabetically or by creator),
or even filter it like the WA addon ingame.

**Comment by darthelit** [comment]
If no one is working on this I could attempt to get started on this.

**Comment by mrbuds** [comment]
Pull Requests are welcome :)

**Comment by darthelit** [comment]
Is there a preference on the UX for this? A table header that is clickable or a dropdown that has different options A-Z & Z-A for aura name and creator

**Comment by LootFever** [comment]
If my input counts for anything. I would popbably got with the dropdown (aura name v, aura name ^, creator v, ...)
It takes up less space and the header would imply that u can sort by version number wich makes no sense imo.

**Comment by mrbuds** [comment]
> 
> 
> Is there a preference on the UX for this? A table header that is clickable or a dropdown that has different options A-Z & Z-A for aura name and creator

I think clickable headers feels more natural and won't saturate the UI, not all headers have to be sortable

**Comment by darthelit** [comment]
I'm indifferent. I've seen and done it both ways, granted not in Vue so they will take a little longer just so I can learn some basic Vue.js.

The dropdown option is the easiest of the two options, less reactive styling needed.

**Comment by darthelit** [comment]
I'm new to Vue, can someone explain to me, possibly over discord how to update the auras array dynamically? Just trying to do a simple sort and I can't get the UI to update with the new sorted array.

**Comment by cont1nuity** [comment]
Updating parameters in the data provider functions should update the table automatically, iirc. So, if you add the sorting to those functions, the table should re-populate with the sorted data when you change the sort value.

**Comment by bentsku** [comment]
Hello !
I've been picking up this issue too, and I've came up with some prototype. I've made a gif to show the result, there's still some styling to do (and alignment with the auras columns under), and to give the headers some names (translated also).
I didn't want to rewrite the whole aura list as a table yet, but maybe that'd make sense ?

I'd like to get some feedback about it, if possible! If you'd like some different style for the header's text, separators, anything really. 
And also which column to sort. 

Thanks! 
![ezgif-4-86fada137155](https://user-images.githubusercontent.com/42031100/94991990-06ef4500-0587-11eb-9425-209be9602508.gif)

**Comment by mrbuds** [comment]
Styling is the last thing to review, can you make a PR to discuss the implementation ?

**Comment by darthelit** [comment]
Looks good from the GIF. I've been preoccupied with work and family that I haven't spent enough time learning Vue to fully understand what I needed to do to get it to update the UI properly,

**Comment by bentsku** [comment]
Thanks! No problem, I just had some time and I've been working with Vue for about two years now, it's nice to work on something fresh sometimes. I guess the big part of Vue is how computed properties works. Their official documentation is very thorough, if one day you're back at it!

**Comment by mrbuds** [comment]
Sorting is now implemented
