### ISSUE TITLE
Error message on WA Companion and no plater list

### ISSUE THREAD

**Issue by cortx-fr** [WeakAuras/WeakAuras-Companion#695]
Operating System: Windows

Companion Version: 3.0.1

Companion App Console Log:
app.9981f8d7.js:1 validateWowpath
app.9981f8d7.js:1 {}
app.9981f8d7.js:1 buildAccountList
app.9981f8d7.js:1 buildVersionList
app.9981f8d7.js:1 buildAccountList
app.9981f8d7.js:1 promisesWagoCallsComplete
app.9981f8d7.js:1 promisesWagoDataCallsComplete
app.9981f8d7.js:1 writeAddonData
app.9981f8d7.js:1 updaterHandler: update-not-available
app.9981f8d7.js:1 updaterHandler: checkForUpdates
app.9981f8d7.js:1 Backup: Plater-_retail_#GUITOU87-20200608014454.zip saved
app.9981f8d7.js:1 {}
app.9981f8d7.js:1 promisesWagoCallsComplete
app.9981f8d7.js:1 promisesWagoDataCallsComplete
app.9981f8d7.js:1 no data received for Mage_AfenarUI
app.9981f8d7.js:1 writeAddonData
app.9981f8d7.js:1 {}
app.9981f8d7.js:1 promisesWagoCallsComplete
app.9981f8d7.js:1 promisesWagoDataCallsComplete
app.9981f8d7.js:1 no data received for Mage_AfenarUI
app.9981f8d7.js:1 writeAddonData
app.9981f8d7.js:1 {}
app.9981f8d7.js:1 promisesWagoCallsComplete
app.9981f8d7.js:1 promisesWagoDataCallsComplete
app.9981f8d7.js:1 no data received for Mage_AfenarUI
app.9981f8d7.js:1 writeAddonData
DevTools failed to parse SourceMap: file:///C:/Users/Thomas/AppData/Local/Programs/weakauras-companion/resources/app.asar/uri.all.js.map

Describe the bug: Error message on WA Companion and no plater list

To Reproduce
In WA Companion just ask for an update.

Screenshots
https://i.imgur.com/WGFjKPD.png

**Comment by cont1nuity** [comment]
Please upload your **World of Warcraft\_retail_\WTF\Account\GUITOU87\SavedVariables\Plater.lua** here.

**Comment by cortx-fr** [comment]
Hello;

I've no file into: E:\Jeux\World of Warcraft\_retail_\WTF\Account\GUITOU87\SavedVariables
[Plater.lua.txt](https://github.com/WeakAuras/WeakAuras-Companion/files/4978752/Plater.lua.txt)

**Comment by cont1nuity** [comment]
Thank you. There was a typo above, missing a slash between Warcraft and _retail_, but the file you provided looks correct to me.

**Comment by cont1nuity** [comment]
You have some broken profiles. Seems like some mod import went wrong at some point in time. Please use the file below to replace your existing Plater.lua in your WTF\Account\GUITOU87\SavedVariables\ folder. Make sure to exit WoW before you do this.
[Plater.lua.txt](https://github.com/WeakAuras/WeakAuras-Companion/files/4978826/Plater.lua.txt)

**Comment by cortx-fr** [comment]
That's work like a charm.
Thank you
