### ISSUE TITLE
Companion not updating after updating in-game

### ISSUE THREAD

**Issue by jabramek** [WeakAuras/WeakAuras-Companion#70]
**Operating System:**
- [X ] Windows
- [ ] Mac
- [ ] Linux

**Companion Version:**
1.0.19

**WeakAuras Version:**
```
2.11.0
```
After Fetching Updates via Companion and then updating in-game via WA Addon, the Companion is still telling me "9 updates ready for in-game installation.". I'm not an expert on any of this but I am assuming once your WA's are updated the list is supposed to clear? In which case, mine isn't and is reminding me that I have updates to install.

**Comment by mrbuds** [comment]
Companion get the state of your auras by reading weakauras's savedvariable.
This file is not updated in real time, wow save it on each loading screen, so you have to /reload in game for Companion to see your changes.

If it doesn't help, open a new ticket but this time answer the questions, don't delete them.
