### ISSUE TITLE
[Feature Request] Add ability to hide dock icon for Mac App

### ISSUE THREAD

**Issue by JayTheMarketer** [WeakAuras/WeakAuras-Companion#732]
Please add the ability to hide the dock icon in the Mac app. It’s a relatively simple addition with Electron. I am not set up to contribute, but I could potentially make the updates via pull request (if that is something that is allowed).

**Comment by mrbuds** [comment]
I don't own a mac so a PR is very welcome

**Comment by JayTheMarketer** [comment]
Submitted the PR. I realized the the dock icon was a red herring — it didn’t have the standard functionality. Namely, if the app was minimized, clicking on the dock icon did not maximize it. The only way to get it back was via clicking the menu bar icon. As such, I updated the macOS build options to configure it as a menu bar only application — which was how it was functioning anyway.

**Comment by JayTheMarketer** [comment]
yeah, absolutely. we’d just need one white and one black for light and dark mode.

**Comment by Stanzilla** [comment]
@JayTheMarketer I got it :)

**Comment by JayTheMarketer** [comment]
thanks @Stanzilla! Also, just as a heads up, I added a Cask for this in Homebrew — for convenience of us Mac users 🍎

**Comment by layday** [comment]
It is *extremely* unusual for a Mac app to be 'minimised' to the menu bar and to be hidden from the Dock and the app switcher (cmd-tab) altogether.  Electron supports minimising apps to the Dock out of the box, so if that wasn't happening here, it's because something in `background.js` was tripping it up.

**Comment by JayTheMarketer** [comment]
@layday its actually quite common -- especially among apps that exist primarily to run in the background and update existing files. I have several in my menu bar currently, such as Google Drive, Dropbox, OneDrive, Alfred, and Amphetamine.

**Comment by layday** [comment]
None of those apps have a window of their own (other than a prefs window) and integrate either with the Finder or with Spotlight.  Clicking on their menu bar icon does not open a window; it opens a menu.

**Comment by JayTheMarketer** [comment]
Dash and Numi. Those are the other two in my menu bar that open an app, not a preference menu, and have no dock icon. It's not uncommon and makes a whole lot of sense for this use case.

**Comment by layday** [comment]
It's not the default behaviour in either of those apps and I would imagine it's not the default for a reason.  I've been a Mac user for most of my life and I found the way WAC operates very unintituive.  It could be that my expectations are warped.
