### ISSUE TITLE
Weakauras completely broken

### ISSUE THREAD

**Issue by albinvalastig** [WeakAuras/WeakAuras-Companion#774]
Hello!

Since three hours ago my weakauras and the addon itself have been completely broken. Some of my auras refuse to load, even though they have been for several months before this and at this point I can't even open the addon ingame. When I reload my client random amounts of my weakauras show up, sometimes it's 4 of them and so on. Sometimes even everything loads properly but even though it appears to work I cannot open the addon.

Things I've tried up until the time of writing this:

Reinstalling Wow, both completely fresh and once with my WTF and Addons folders pasted in afterwards.
Reinstalling the Addon and reimporting the Weakauras.

None of this seems to work and I'm now clueless as to what to do next.

Screenshots:
[https://gyazo.com/71886fe106c7d5ea45d99d38039cb2f7](url)
[https://gyazo.com/b4723a8431f09501672338ccf282cef6](url)
[https://gyazo.com/80c9c0de45a438678363d1206aa50fad](url)

[Weakaura.zip](https://github.com/WeakAuras/WeakAuras-Companion/files/5143236/Weakaura.zip)

**Comment by mrbuds** [comment]
Please answer the question from the issue template, notably the questions about error logs using bugsack
