### ISSUE TITLE
[Windows] App installation stuck (error)

### ISSUE THREAD

**Issue by baylrock** [WeakAuras/WeakAuras-Companion#794]
**Operating System:**
- [x] Windows
- [ ] Mac
- [ ] Linux

**Companion Version:**
```
v.3.0.4
```

**Companion App Console Log:**
```
> npm run dev

<s> [webpack.Progress] 98% after emitting CopyPlugin
 DONE  Compiled successfully in 3611ms7:05:43 PM

<s> [webpack.Progress] 100%


  App running at:
  - Local:   http://localhost:8080/
  - Network: http://192.168.0.236:8080/

  Note that the development build is not optimized.
  To create a production build, run npm run build.

-  Bundling main process...
 DONE  Compiled successfully in 1198ms7:05:44 PM

  File                      Size                     Gzipped

  dist_electron\index.js    2087.42 KiB              411.43 KiB

  Images and other types of assets omitted.

 INFO  Launching Electron...
19:05:44.571 > App starting...
(node:24404) ExtensionLoadWarning: Warnings loading extension at C:\Users\....\AppData\Roaming\weakauras-companion\extensions\nhdogjmejiglipccpnnnanhbledajbpd: Unrecognized manifest key 'browser_action'. Unrecognized manifest key 'update_url'. Permission 'contextMenus' is unknown or URL pattern is malformed.
```

**Describe the bug**
Installation freezes on windows right after installation app started. 
I tried to run dev env - you can see logs above. After ExtensionLoadWarning nothing happens.
I tried 3.0.0 version and it worked just fine.

**To Reproduce**
1. Download windows version from https://weakauras.wtf/ or Git releases
2. Run exe

**Expected behavior**
App Installed.

**Comment by mrbuds** [comment]
From the information you gave i think this is a known issue from electron-builder https://github.com/electron-userland/electron-builder/issues/4057
A workaround is to delete registry key at Computer\HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Uninstall
