### ISSUE TITLE
[Feature request? Refactoring?] VueJS best practices

### ISSUE THREAD

**Issue by bentsku** [WeakAuras/WeakAuras-Companion#813]
Hello!

I've been working a bit on the project, and I've noticed some parts of it don't follow the VueJS best practices. In particular the mutation of nested props (the config object in the Config page child), and the usage of $parent methods. 

I don't exactly know what the solution would be without bloating the project too much, but maybe a centralised state object, VueX or any suggestions would be good to avoid those practices.

I'd be interested to work on this, but I'm not sure you would be interested in it ? I hope this doesn't come across as impolite, I just have a bit of time on my hands. 

I haven't worked with Vue 3 either yet, maybe this can be part of the discussion also.

If you have any suggestions about how to tackle this, maybe we could use this to discuss about the possibilities ?

**Comment by Stanzilla** [comment]
Feel free to tackle this, both buds and I haven't really worked with JS before this project so any help is welcome :)
