### ISSUE TITLE
Dragging window while app is loading **can** break mouseup event

### ISSUE THREAD

**Issue by mrbuds** [WeakAuras/WeakAuras-Companion#84]
**Operating System:**
- [x] Windows

**Companion Version:**
1.1.2-beta3

**Companion App Console Log:**
no error

**Describe the bug**
Window can stick to mouse cursor when moving it while loading

**To Reproduce**
move window during loading and have bad luck
happened to me once, not easy to reproduce
saw someone on discord with same problem (vardex?)

**Note**
alt+f4 fix it kappa

**Comment by Nightwarden24** [comment]
Do you mean a bug that Putro reported in channel in Discord?

![](https://i.gyazo.com/aad666c20c5522ea3fe54214e326152f.gif)

I encountered this once too. I remember thinking it was better to disable dragging a window in menu area.

**Comment by mrbuds** [comment]
Yes, but i don't think the fact that the click was made on a menu button matters.
This is what was changed to make the whole area draggable <https://github.com/WeakAuras/WeakAuras-Companion/commit/11f79f922868a984e7de878075014795589af959>
In some circumstance the event listener for "mouseup" is wiped while the mouse is still down
