### ISSUE TITLE
WeakAuras Companion shows updates from up to 21 days ago, with me fetching updates multiple times a day.

### ISSUE THREAD

**Issue by NANTOIANER** [WeakAuras/WeakAuras-Companion#853]
**Operating System:**
- [x] Windows
- [ ] Mac
- [ ] Linux
**Companion Version:**
3.0.6
**Companion App Console Log:**
app.472327b7.js:1 validateWowpath
app.472327b7.js:1 buildAccountList
app.472327b7.js:1 buildVersionList
app.472327b7.js:1 buildAccountList
app.472327b7.js:1 updaterHandler: update-not-available
app.472327b7.js:1 updaterHandler: checkForUpdates
app.472327b7.js:1 promisesWagoCallsComplete
app.472327b7.js:1 promisesWagoDataCallsComplete
app.472327b7.js:1 writeAddonData
app.472327b7.js:1 Backup: Plater-_retail_#NANTOIANER-20201103003258.zip saved
app.472327b7.js:1 promisesWagoCallsComplete
app.472327b7.js:1 promisesWagoDataCallsComplete
app.472327b7.js:1 no data received for cD7_t3TAu
app.472327b7.js:1 no data received for gk8RnGTSD
app.472327b7.js:1 writeAddonData
app.472327b7.js:1 Backup: Plater-_retail_#NANTOIANER-20201103103501.zip saved
app.472327b7.js:1 Backup: WeakAuras-_retail_#NANTOIANER-20201103103501.zip saved
**WeakAuras Version:**
3.0.5
**WeakAuras Errors:**
No errors.
**Describe the bug**
I'm fetching updates daily and the majority of the time Companion will tell me "everything's up to date already". However sometimes I fetch updates and the app will show updates from anything between 2 and 21 days ago.
**To Reproduce**
Behavior seems random, so reproduction is inconclusive. 
1. Fetch updates
2. Mouse over latest version to see change date.
3. Occasionally see 

**Expected behavior**
Ideally I wanna be able to use a WA update through Companion once it hits Wago, not up to 3 weeks later.
**Attachments:**
![WeakAuras_Companion_myWTirw1lH](https://user-images.githubusercontent.com/73881929/97976380-ea833a00-1dca-11eb-9172-d22c7eb5cdeb.png)
![WeakAuras_Companion_Oh3JcxilXZ](https://user-images.githubusercontent.com/73881929/97976386-ec4cfd80-1dca-11eb-9090-75df3e5714d0.png)
![WeakAuras_Companion_pG7gMN4u1f](https://user-images.githubusercontent.com/73881929/97976393-eeaf5780-1dca-11eb-9952-10c6deb8928b.png)
![Wow_A84y31vnpL](https://user-images.githubusercontent.com/73881929/97976397-efe08480-1dca-11eb-8d53-cf7c13c3f68c.png)
![Wow_UmdDBqXlI1](https://user-images.githubusercontent.com/73881929/97976401-f1aa4800-1dca-11eb-95c5-7fd3bed4bced.png)
**config.json**
[configJSON.zip](https://github.com/WeakAuras/WeakAuras-Companion/files/5480720/configJSON.zip)
**WeakAuras.lua**
[WeakAurasLUA.zip](https://github.com/WeakAuras/WeakAuras-Companion/files/5480722/WeakAurasLUA.zip)

**Comment by NANTOIANER** [comment]
Quick update:
Usually I just applied the updates in-game regardless and didn't pay further attention to the issue. This time I left Companion open for a while and didn't update the WeakAuras in-game.

Seems like 2 hours later the timers corrected themselves for the same two WeakAuras. Now show 5 and 6 hours ago, instead of 4 and 7 days ago.

![WeakAuras_Companion_z9BxkqhAjO](https://user-images.githubusercontent.com/73881929/97977457-88c3cf80-1dcc-11eb-9e8e-d39676b087fc.png)

**Comment by mrbuds** [comment]
![image](https://user-images.githubusercontent.com/189656/97989775-4d7ecc00-1ddf-11eb-9004-0c4cf92659af.png)

![image](https://user-images.githubusercontent.com/189656/97989860-70a97b80-1ddf-11eb-9f41-415302946b29.png)

I don't see what's wrong with companion showing last update is 1 week old when last update on wago is 1 week old

**Comment by mrbuds** [comment]
mhm wait

**Comment by mrbuds** [comment]
Is it a tooltip issue or companion showing you an update 1 week later ?

**Comment by mrbuds** [comment]
I think your issue come from the way tooltip is refreshed here https://github.com/WeakAuras/WeakAuras-Companion/blob/437764f4d36d27f914eb3d155d8f8b3859fd4e01/src/components/UI/Aura.vue#L62
@bentsku would you know how to better fix it than the current @mouseover trick ?

**Comment by cont1nuity** [comment]
Wago payload seems to be correct, as S1tvLLBV7 was updated this morning and both config.js show `"modified": "2020-11-03T05:30:38.956Z",` and both have the identical import string available.
Could this be a timezone/locale issue?

**Comment by bentsku** [comment]
Yes, I think the content of the tooltip is calculated during render.
If the component is rerendered, the time would update. 
I guess using a computed property could solve it, combined with the mouseover method to update the currentValue. I'll try to work something.

**Comment by NANTOIANER** [comment]
> @mrbuds Is it a tooltip issue or companion showing you an update 1 week later ?

After I posted my update directly following my initial post, I'm pretty confident it pulls the correct (latest) version from Wago, just the mouseover tooltip being incorrect.

**Comment by bentsku** [comment]
I think we don't even need a computed prop, I'll submit a PR shortly.

**Comment by bentsku** [comment]
And by the way, really sorry @NANTOIANER for not understand the issue earlier on Discord. I didn't get the underlying problem you were talking about, with updating every day and old auras appearing.
