### ISSUE TITLE
"Launch client with your Computer" option doesn't work

### ISSUE THREAD

**Issue by panseit** [WeakAuras/WeakAuras-Companion#857]
"Launch client with your Computer" option doesn't get respected and the app doesn't open when computer starts. The app is installed and launched as Administrator.

**Comment by mrbuds** [comment]
Hey, so first you should not install any app with administrator rights that is not a driver.
And you didn't answer any question from the issue template, i have no idea what you are talking about, there is no such option in companion app.

**Comment by cont1nuity** [comment]
![image](https://user-images.githubusercontent.com/10164755/98255271-85bc1100-1f7d-11eb-9f29-4583dd191a3c.png)
This option, I think.

**Comment by panseit** [comment]
I installed the app with and without administrator rights to see if for some reason that blocks it. Yeah my bug report was really poor written sorry. @cont1nuity is correct. That is the setting I'm talking about

**Comment by mrbuds** [comment]
Ok i though it was an error shown by your OS.

> Yeah my bug report was really poor written sorry

It would help if you answer issue template question as i asked.
I don't know which operating system do you use.
I don't know if console show errors when you click on the checkbox.

We use <https://github.com/Teamwork/node-auto-launch> which didn't get any update for 3 years and have a lot of issue tickets and PR open.

**Comment by panseit** [comment]
**Operating System:**
- Windows 10 20H2 Version

**Companion Version:**
- 3.0.6

**Companion App Console Log:**
app.472327b7.js:1 validateWowpath
app.472327b7.js:1 buildAccountList
app.472327b7.js:1 buildVersionList
app.472327b7.js:1 buildAccountList
app.472327b7.js:1 updaterHandler: update-not-available
app.472327b7.js:1 updaterHandler: checkForUpdates
app.472327b7.js:1 promisesWagoCallsComplete
app.472327b7.js:1 promisesWagoDataCallsComplete
app.472327b7.js:1 writeAddonData
app.472327b7.js:1 promisesWagoCallsComplete
app.472327b7.js:1 promisesWagoDataCallsComplete
app.472327b7.js:1 writeAddonData
app.472327b7.js:1 updaterHandler: checking-for-update
app.472327b7.js:1 updaterHandler: update-not-available
app.472327b7.js:1 updaterHandler: checkForUpdates
app.472327b7.js:1 promisesWagoCallsComplete
app.472327b7.js:1 promisesWagoDataCallsComplete
app.472327b7.js:1 writeAddonData
app.472327b7.js:1 Backup: Plater-_retail_##1-20201105094941.zip saved
app.472327b7.js:1 promisesWagoCallsComplete
app.472327b7.js:1 promisesWagoDataCallsComplete
app.472327b7.js:1 writeAddonData
app.472327b7.js:1 Backup: Plater-_retail_##1-20201105095419.zip saved
app.472327b7.js:1 updaterHandler: checking-for-update
app.472327b7.js:1 updaterHandler: update-not-available
app.472327b7.js:1 updaterHandler: checkForUpdates
app.472327b7.js:1 promisesWagoCallsComplete
app.472327b7.js:1 promisesWagoDataCallsComplete
app.472327b7.js:1 writeAddonData
app.472327b7.js:1 Backup: Plater-_retail_##1-20201105114854.zip saved
app.472327b7.js:1 promisesWagoCallsComplete
app.472327b7.js:1 promisesWagoDataCallsComplete
app.472327b7.js:1 writeAddonData
app.472327b7.js:1 Backup: Plater-_retail_##1-20201105124729.zip saved
app.472327b7.js:1 updaterHandler: checking-for-update
app.472327b7.js:1 updaterHandler: update-not-available
app.472327b7.js:1 updaterHandler: checkForUpdates
app.472327b7.js:1 promisesWagoCallsComplete
app.472327b7.js:1 promisesWagoDataCallsComplete
app.472327b7.js:1 writeAddonData
app.472327b7.js:1 Backup: Plater-_retail_##1-20201105133143.zip saved
app.472327b7.js:1 promisesWagoCallsComplete
app.472327b7.js:1 promisesWagoDataCallsComplete
app.472327b7.js:1 writeAddonData
app.472327b7.js:1 Backup: Plater-_retail_##1-20201105144440.zip saved
app.472327b7.js:1 updaterHandler: checking-for-update
app.472327b7.js:1 updaterHandler: update-not-available
app.472327b7.js:1 updaterHandler: checkForUpdates
app.472327b7.js:1 promisesWagoCallsComplete
app.472327b7.js:1 promisesWagoDataCallsComplete
app.472327b7.js:1 writeAddonData
app.472327b7.js:1 Backup: Plater-_retail_##1-20201105151547.zip saved
app.472327b7.js:1 promisesWagoCallsComplete
app.472327b7.js:1 promisesWagoDataCallsComplete
app.472327b7.js:1 writeAddonData
app.472327b7.js:1 Backup: Plater-_retail_##1-20201105160559.zip saved

It doesn't pop any errors or anything else. The setting just simply doesn't work at all.

**Comment by mrbuds** [comment]
Alright thank you for the report, i'll if there are better alternatives than the node module we use for this

**Comment by panseit** [comment]
Sorry again for the initial stupidly written bug report. Thank you for your work :)

**Comment by mrbuds** [comment]
@panseit can you try with this build ? https://github.com/WeakAuras/WeakAuras-Companion/suites/1456714511/artifacts/24884101

**Comment by panseit** [comment]
Yeap. Now the app starts with Windows :)
