### ISSUE TITLE
Mac "Error in updater.,"  

### ISSUE THREAD

**Issue by disc0infern0** [WeakAuras/WeakAuras-Companion#86]
Guessing here that a new Mac version is available, but the client was not able to update itself.
the user account running the client, is an Admin,  but perhaps there is a prompt being suppressed that is asking for an Admin password to continue? 

**Operating System:**
- [ ] Windows
- [X ] Mac
- [ ] Linux

**Companion Version:**
1.1.1
Check the bottom left of the "About" panel in the app.
```

**Companion App Console Log:**
```
Press Ctrl+Shift+I to open the console and copy-paste everything here
updaterHandler: update-available - undefined.          renderer.js:1
updaterHandler: error - {}

**WeakAuras Version:**
2.11.1
/run print(WeakAuras.versionString) in-game.
```

**WeakAuras Errors:**
```
1. Install https://mods.curse.com/addons/wow/BugSack
2. Install https://mods.curse.com/addons/wow/bug-grabber
3. Try to do whatever it is you're having a problem with again
4. Check your minimap for an icon that looks like a bag.  Is it green, or is it red?
   • GREEN
      • WeakAuras is working correctly.
      • Either you found a behavioral bug, or you are just doing it wrong :)
      • Explain the steps you took, and we will try to figure out what happened.
   • RED 
     • There are error messages. Click on the red bag to see them.
     • Copy & Paste here all of the error messages (there may be more than one, click the 'previous' button on the dialog to see previous ones
```

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Include a .zip file containing:**
`%programfiles%\World of Warcraft\_retail_\WTF\Account\<AccountName>\SavedVariables\WeakAuras.lua`
AND
`%appdata%\weakauras-companion\config.json`

**Comment by mrbuds** [comment]
I don't own a mac, and this error message is not telling anything sadly.
On next version, updater error will be more verbose in the console.

**Comment by mrbuds** [comment]
We figured that auto-updater won't work on mac until it's signed with an Apple certificate.
Starting with 1.1.4-beta3, updater won't download updates on macs, but will notify if an update is available.
