### ISSUE TITLE
Weak Auras Bug (Can't open config menu after importing legion weak aura)

### ISSUE THREAD

**Issue by Damenkata** [WeakAuras/WeakAuras-Companion#865]
**Operating System:**
- [ +] Windows
- [ ] Mac
- [ ] Linux

**Companion Version:**
3.0.6
Check the bottom left of the "About" panel in the app.
```

**Companion App Console Log:**
```
Press Ctrl+Shift+I to open the console and copy-paste everything here
validateWowpath
app.472327b7.js:1 buildAccountList
app.472327b7.js:1 buildVersionList
app.472327b7.js:1 buildAccountList
app.472327b7.js:1 updaterHandler: update-not-available
app.472327b7.js:1 updaterHandler: checkForUpdates
app.472327b7.js:1 promisesWagoCallsComplete
app.472327b7.js:1 promisesWagoDataCallsComplete
app.472327b7.js:1 writeAddonData
app.472327b7.js:1 Uncaught (in promise) TypeError: t.replace is not a function
    at app.472327b7.js:1
    at Array.forEach (<anonymous>)
    at app.472327b7.js:1
    at Array.forEach (<anonymous>)
    at app.472327b7.js:1
    at Array.forEach (<anonymous>)
    at a.writeAddonData (app.472327b7.js:1)
(anonymous) @ app.472327b7.js:1
(anonymous) @ app.472327b7.js:1
(anonymous) @ app.472327b7.js:1
writeAddonData @ app.472327b7.js:1

**WeakAuras Version:**
9.0.1
/run print(WeakAuras.versionString) in-game.
3.0.6

**WeakAuras Errors:**
1x WeakAuras\RegionTypes\Icon.lua:236: attempt to index local 'id' (a number value)
[string "@WeakAuras\RegionTypes\Icon.lua"]:236: in function `create'
[string "@WeakAuras\WeakAuras-3.0.6.lua"]:2833: in function `SetRegion'
[string "@WeakAuras\WeakAuras.lua"]:2759: in function <WeakAuras\WeakAuras.lua:2665>
[string "@WeakAuras\WeakAuras.lua"]:2794: in function `Add'
[string "@WeakAuras\WeakAuras.lua"]:2325: in function `load'
[string "@WeakAuras\WeakAuras.lua"]:2332: in function `AddMany'
[string "@WeakAuras\WeakAuras.lua"]:1009: in function <WeakAuras\WeakAuras.lua:981>

[string "@WeakAuras\WeakAuras-3.0.6.lua"]:1131: in function <WeakAuras\WeakAuras.lua:1082>

**Describe the bug**
The bug is that I cannot open the config menu in-game , after I accidentally imported an outdated (Legion) weak aura while I was trying to get some new weak auras. I tried to delete the specific weak aura in the .lua file myself, I opened the .lua file with Notepad and deleted the code segment which I thought was the problem causing weak aura and then I restarted WoW. But even after that nothing happened, I still can't open the config menu with the /wa command.

**To Reproduce**

**Expected behavior**
I expect to receive help regarding my problem in WoW , which is not being able to open config menu in-game due to accidentally importing an outdated (Legion) weak aura.

**Screenshots**
No screenshots needed.

**Include a .zip file containing:**
[Weak Auras files.zip](https://github.com/WeakAuras/WeakAuras-Companion/files/5521735/Weak.Auras.files.zip)

`%programfiles%\World of Warcraft\_retail_\WTF\Account\<AccountName>\SavedVariables\WeakAuras.lua`

AND
`%appdata%\weakauras-companion\config.json`

**Comment by InfusOnWoW** [comment]
Not a companion bug at all.
