### ISSUE TITLE
Wago Texture Import

### ISSUE THREAD

**Issue by 1ps3** [WeakAuras/WeakAuras-Companion#87]
A really nice feature to go along with the Companion's ability to update auras from wago would be to have it also be able to import textures. This feature would be extremely helpful to users since they wouldn't have to worry about importing textures themselves. Obviously if the Companion takes over the need for downloading textures then it would probably have to come with it's own file system/style which I don't think is a bad thing since authors could just reference the expected file system. 

There's probably some naming issue here, and the only idea that I've come up with is organising textures by user. Organising by wago users limits the opportunity for overlapping names.

**Comment by 1ps3** [comment]
Obviously this isn't an issue when it comes to frogs since they're quite well named.
![zjmh5au511x11](https://user-images.githubusercontent.com/15392657/51908800-db65a000-241e-11e9-8623-a7d4f1b4a861.jpg)

**Comment by Vardex** [comment]
I would also like a support from custom sounds along custom textures.

**Comment by mrbuds** [comment]
RGPD killed that feature
