### ISSUE TITLE
Regression: Update check on start no longer works

### ISSUE THREAD

**Issue by Stanzilla** [WeakAuras/WeakAuras-Companion#886]
**Operating System:**
- [x] Windows
- [x] Mac
- [ ] Linux

**Companion Version:**
```
3.1.1
```

**Companion App Console Log:**
```
Press Ctrl+Shift+I to open the console and copy-paste everything here
```

**WeakAuras Version:**
```
3.1.2
```

**WeakAuras Errors:**
```
1. Install https://mods.curse.com/addons/wow/BugSack
2. Install https://mods.curse.com/addons/wow/bug-grabber
3. Try to do whatever it is you're having a problem with again
4. Check your minimap for an icon that looks like a bag.  Is it green, or is it red?
   • GREEN
      • WeakAuras is working correctly.
      • Either you found a behavioral bug, or you are just doing it wrong :)
      • Explain the steps you took, and we will try to figure out what happened.
   • RED 
     • There are error messages. Click on the red bag to see them.
     • Copy & Paste here all of the error messages (there may be more than one, click the 'previous' button on the dialog to see previous ones
```

**Describe the bug**

**To Reproduce**
1. Start app
2. Let initial check finish
3. Click refresh

**Expected behavior**
The initial check on app start does not find aura updates, manually pressing refresh does

**Screenshots**

**Include a .zip file containing:**
`%programfiles%\World of Warcraft\_retail_\WTF\Account\<AccountName>\SavedVariables\WeakAuras.lua`
AND
`%appdata%\weakauras-companion\config.json`

**Comment by mrbuds** [comment]
Error is `Uncaught TypeError: err is not a function` at this line https://github.com/WeakAuras/WeakAuras-Companion/blob/e36b18d0b20d8e078eccc8dde997f9831a4ecf3d/src/components/libs/utilities.js#L59

**Comment by bentsku** [comment]
> Error is `Uncaught TypeError: err is not a function` at this line https://github.com/WeakAuras/WeakAuras-Companion/blob/e36b18d0b20d8e078eccc8dde997f9831a4ecf3d/src/components/libs/utilities.js#L59
> 
> 

I think the error comes from the fact that `err` is re-assigned. The second argument of the promise should be `reject` and not `err`. We re-reference with the `err` of the `fs` call. I think you could rename the second argument of the promise reject and reject the promise instead of `done(false)`.
I don't understand how we regressed on this one ?

**Comment by mrbuds** [comment]
Issue happen when you don't have Plater or WeakAuras installer

**Comment by bentsku** [comment]
Ha right it was the fix that created the addon folder if you didn't have it. Thanks!
