### ISSUE TITLE
Plater mods update

### ISSUE THREAD

**Issue by Addonman** [WeakAuras/WeakAuras-Companion#887]
**Operating System:**
- [x ] Windows
- [ ] Mac
- [ ] Linux

**Companion Version:**
``` 3.11
Check the bottom left of the "About" panel in the app.
```

**Companion App Console Log:**
```
Press Ctrl+Shift+I to open the console and copy-paste everything here
```

**WeakAuras Version:**
```
/run print(WeakAuras.versionString) in-game.
```
3.1.2-5-gdd58908

**Describe the bug**
Companion is that i need to update Plater mod when i already have that mod updated
https://wago.io/uwe9CEwMm

**To Reproduce**
1. Go to Companion
2. Click on Update
3. Go in game
4. No updae there

**Expected behavior**
Detecting what version of mod i have in game and acting accordingly

**Screenshots**

**Include a .zip file containing:**
`%programfiles%\World of Warcraft\_retail_\WTF\Account\<AccountName>\SavedVariables\WeakAuras.lua`
AND
`%appdata%\weakauras-companion\config.json`

**Comment by cont1nuity** [comment]
please check all your other Plater profiles. the companion checks all profiles, used or not.

**Comment by Addonman** [comment]
Really?I do need to consolidate it into one so if thats intended behavior it just might be reason.
