### ISSUE TITLE
Automatic check on startup doesn't refresh local version before checking for updates

### ISSUE THREAD

**Issue by cremor** [WeakAuras/WeakAuras-Companion#904]
**Operating System:**
Windows

**Companion Version:**
3.1.1

**Companion App Console Log:**
```
validateWowpath
app.083a595c.js:1 buildAccountList
app.083a595c.js:1 buildVersionList
app.083a595c.js:1 buildAccountList
app.083a595c.js:1 Uncaught TypeError: o is not a function
    at app.083a595c.js:1
    at FSReqCallback.oncomplete (fs.js:160)
app.083a595c.js:1 updaterHandler: update-not-available
app.083a595c.js:1 updaterHandler: checkForUpdates
app.083a595c.js:1 promisesWagoCallsComplete
app.083a595c.js:1 promisesWagoDataCallsComplete
app.083a595c.js:1 writeAddonData
app.083a595c.js:1 Backup: WeakAuras-_retail_#CREMOR01369-20201226213212.zip saved
app.083a595c.js:1 promisesWagoCallsComplete
app.083a595c.js:1 promisesWagoDataCallsComplete
app.083a595c.js:1 writeAddonData
```

**WeakAuras Version:**
3.1.4

**WeakAuras Errors:**
None

**Describe the bug**
The automatic update check on startup doesn't refresh the already installed version of the weak auras before checking for updates. So it always finds updates that I've already installed ingame.
Pressing the refresh button manually works fine (refreshes versions and then checks for updates).

Also, most likely for the same reason, the automatic check on startup doesn't pick up newly installed weak auras.

**To Reproduce**
1. Make sure an update to a weak aura is available in the app
2. Close the app
3. Install the update ingame
4. Open the app

**Expected behavior**
No update should be shown any more.

**Screenshots**
Shouldn't be needed.

**Include a .zip file containing:**
[WeakAuras.zip](https://github.com/WeakAuras/WeakAuras-Companion/files/5744339/WeakAuras.zip)

**Comment by SirNorek** [comment]
Seconded. I update daily usually, I KNOW I installed these updates, app shows them as still available to update, hit refresh manually and they go away.

**Comment by Stanzilla** [comment]
Yep, confirmed
