### ISSUE TITLE
WA Companion shows available updates for Plater Mods/Scripts that already are updated but where the old version is still in "recently removed"

### ISSUE THREAD

**Issue by Beet4** [WeakAuras/WeakAuras-Companion#912]
**Operating System:**
- [X] Windows
- [ ] Mac
- [ ] Linux

**Companion Version:**
```
3.1.1
```

**Companion App Console Log:**
```
validateWowpath
app.083a595c.js:1 buildAccountList
app.083a595c.js:1 buildVersionList
app.083a595c.js:1 buildAccountList
app.083a595c.js:1 updaterHandler: update-not-available
app.083a595c.js:1 updaterHandler: checkForUpdates
app.083a595c.js:1 promisesWagoCallsComplete
app.083a595c.js:1 promisesWagoDataCallsComplete
app.083a595c.js:1 writeAddonData```
```

**WeakAuras Version:**
```
3.1.4
```

**Describe the bug**
WA Companion shows that there are updates available for plater mods and scripts that has been removed but still are in recently removed mods/scripts in plater. The mods and scripts has already been updated so the updated versions are active but WA Companion keeps saying that they are outdated but looking at the version number WA Companion says it's referring to the mods/scripts that are in "recently removed" or what you can call it.

This is very annoying since Plater places previous versions of updated mods/scripts in the recently removed for 30 days or so so it will complain about mods/Scripts being updated for 30 days after being updated or removed.

**To Reproduce**
1. Open plater
2. Install outdated mod/script
3. Remove it
4. WA Companion shows that there is an updated for a removed mod/script.

**Expected behavior**
Once an mod/script is removed it should no longer want to update it.

**Screenshots**
![image](https://user-images.githubusercontent.com/38279393/103302146-39340580-4a03-11eb-94d1-154a5caf09f0.png)
![image](https://user-images.githubusercontent.com/38279393/103302157-3f29e680-4a03-11eb-8331-969c3351daad.png)
![image](https://user-images.githubusercontent.com/38279393/103302174-4a7d1200-4a03-11eb-97ac-ec51cd432a41.png)

**Include a .zip file containing:**
`%programfiles%\World of Warcraft\_retail_\WTF\Account\<AccountName>\SavedVariables\WeakAuras.lua`
AND
`%appdata%\weakauras-companion\config.json`

[WA.zip](https://github.com/WeakAuras/WeakAuras-Companion/files/5751562/WA.zip)

Also included Plater.lua as that is relevant.

**Comment by cont1nuity** [comment]
Trash data is not checked, but all profiles are. You still have unused profiles stored and both your `Beta v8.3` and `Beta v9` profiles, which are used by some chars, have those mods active.
I suggest cleaning up your profiles and deleting unused, such as `HUNTER`, `Ragnaros` and `Mulmuk - Ragnaros`.

**Comment by Beet4** [comment]
Thanks! Make sense now that you say it. I've deleted all old profiles as I only use one same for all characters and the problem is gone.

Thanks for the help. 👍
