### ISSUE TITLE
Companion will not recognize that the plater mod for M+ Colored Mobs is updated to the current version 

### ISSUE THREAD

**Issue by DeleteDH** [WeakAuras/WeakAuras-Companion#927]
Companion will not recognize that the plater mod for M+ Colored Mobs is updated to the current version 

I have tried uninstalling both the companion and the plater addon as well as the mod but it refuses to remove itself from available update once I fetch updates.

**Comment by mrbuds** [comment]
You don't give enough information to get an answer, i guess you still have old version in an unused profile, if that doesn't help please open a new ticket with answers to the template including plater savedvariables
