### ISSUE TITLE
Unable to display account correctly

### ISSUE THREAD

**Issue by SaintSilent** [WeakAuras/WeakAuras-Companion#933]
My account ID cannot be displayed correctly in the software, but it is displayed as garbled code
![QQ图片20210122171500](https://user-images.githubusercontent.com/50226687/105471146-60fe4c80-5cd5-11eb-86ae-44612ce77ef7.png)

**Comment by krazyito65** [comment]
What do you mean by garbled? This is normal names.  

I've been trying for a while to figure out which account belongs to you, but i can't seem to figure out how to know for sure.  The best thing i can think of is to find out which is the 'newest' folder in the WTF/Accounts folder.. but that may not be exactly correct.

Also, the only reason you would have that many accounts, would probably be if you shared the computer, so I'm assuming this is a computer at a gaming cafe, or something similar?

A most accurate way to figure out which is your account is to delete the WTF folder and then login again, yours should be the only one left, but this will remove any addons data that my be there (including any weak aura information)

I would NOT delete the WTF folder unless you are completely fine with losing all your addon information.

**Comment by krazyito65** [comment]
![image](https://user-images.githubusercontent.com/479738/105482044-78a1ea80-5c6d-11eb-95c4-9a11e50e59e7.png)
Something brought up in our discord, is to search the WTF folder for your specific character name.  The account folder that your character name is in would be your account.

**Comment by krazyito65** [comment]
as an example: 
![image](https://user-images.githubusercontent.com/479738/105482241-b999ff00-5c6d-11eb-9bb6-b7c13db74cf9.png)

**Comment by SaintSilent** [comment]
OK，I got it. Thanks a lot.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "WeakAuras/WeakAuras-Companion"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月22日(星期五) 晚上6:52
收件人:&nbsp;"WeakAuras/WeakAuras-Companion"<WeakAuras-Companion@noreply.github.com&gt;;
抄送:&nbsp;"刘铧嵘"<741324262@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [WeakAuras/WeakAuras-Companion] Unable to display account correctly (#933)





 

 Something brought up in our discord, is to search the WTF folder for your specific character name.  The account folder that your character name is in would be your account.
