### ISSUE TITLE
Companion app does not detect any installed WeakAuras

### ISSUE THREAD

**Issue by syndenbock** [WeakAuras/WeakAuras-Companion#935]
**Operating System:**
- [X] Windows
- [ ] Mac
- [ ] Linux

**Companion Version:**
3.1.1

**Companion App Console Log:**
app.083a595c.js:1 validateWowpath
app.083a595c.js:1 buildAccountList
app.083a595c.js:1 updaterHandler: update-not-available
app.083a595c.js:1 updaterHandler: checkForUpdates
app.083a595c.js:1 buildVersionList
app.083a595c.js:1 buildAccountList
app.083a595c.js:1 promisesWagoCallsComplete
app.083a595c.js:1 promisesWagoDataCallsComplete
app.083a595c.js:1 writeAddonData
app.083a595c.js:1 promisesWagoCallsComplete
app.083a595c.js:1 promisesWagoDataCallsComplete
app.083a595c.js:1 no data received for SL-Dungeons
app.083a595c.js:1 no data received for slraid1
app.083a595c.js:1 no data received for InkDhT91D
app.083a595c.js:1 no data received for bfakeys
app.083a595c.js:1 no data received for PXM28wJfq
app.083a595c.js:1 writeAddonData

**WeakAuras Version:**
3.1.8

**WeakAuras Errors:**
No WeakAuras Errors

**Describe the bug**
The WeakAuras companion app stopped detecting any WeakAuras.
I have already tried resetting all companion settings aswell as doing a fresh reinstall of the app.

**To Reproduce**
- Start the Companion App
- Click "Fetch Updates"
- No WeakAuras will be listed and "Everything is up to date" is displayed (I have the option "Show auras without updates" enabled, maybe that one is not working?)

**Expected behavior**
A list of all my WeakAuras with wago.io links to be displayed.

**Screenshots**
![WA Companion](https://user-images.githubusercontent.com/29254285/105634644-65567100-5e5f-11eb-8b3b-985d27259836.png)

**Include a .zip file containing:**
[WA Companion.zip](https://github.com/WeakAuras/WeakAuras-Companion/files/5862512/WA.Companion.zip)

**Comment by mrbuds** [comment]
wago has temporary issue
