### ISSUE TITLE
'Use Companion Beta Channel' check mark not updating

### ISSUE THREAD

**Issue by eldir** [WeakAuras/WeakAuras-Companion#97]
**Operating System:**
- [X] Windows
- [ ] Mac
- [ ] Linux

**Companion Version:**
```
1.1.5.
```

**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Settings'
2. Click on 'Use Companion Beta Channel'
-> No check mark (or uncheck) visible
3. Click on any other check box
-> 'Use Companion Beta Channel' check mark appears or disappears

**Expected behaviour**
Clicking on 'Use Companion Beta Channel' should immediately update the state of the check mark

**Comment by emptyrivers** [comment]
This isn’t the first time that this has happened. @mrbuds, do you know what the root cause of the issue is, and how it can be prevented in the future?

**Comment by mrbuds** [comment]
No there was changes done for this on last release.
I need more information @eldir you didn't provided a screenshot of the problem and the javascript console log
`-> No check mark (or uncheck) visible` => i dont understand this
`Click on any other check box` => click on what?? i dont understand either

**Comment by mrbuds** [comment]
Ok i can reproduce thank you.
It should only happen the first time you run app after updating it, a restart should fix.

I have to be much more careful with this kind of issue indeed.
