### ISSUE TITLE
Can't See my WA's, Error saying: "can't read wago answer."

### ISSUE THREAD

**Issue by dayrokk22** [WeakAuras/WeakAuras-Companion#979]
**Operating System:**
- [x ] Windows
- [ ] Mac
- [ ] Linux

**Companion Version:**
``` version 3.1.1
Check the bottom left of the "About" panel in the app.
```

**Companion App Console Log:**
``` 
Press Ctrl+Shift+I to open the console and copy-paste everything here
```
{"message":"timeout of 15000ms exceeded","name":"Error","stack":"Error: timeout of 15000ms exceeded\n    at e.exports (app://./js/chunk-vendors.a271e257.js:6:94796)\n    at XMLHttpRequest.d.ontimeout (app://./js/chunk-vendors.a271e257.js:52:56769)","config":{"url":"https://data.wago.io/api/check/weakauras","method":"get","headers":{"Accept":"application/json, text/plain, */*","Identifier":"aa812adf","api-key":"2QYa13gza1DMgthIF8BHALUc2EJLK475uhwiMBfHJ7ojLvFPR6359oc1hYEHlJtI"},"params":{"ids":"r1_GTZbHm,ryBp05DHX,SyGtPbRHm,slraid1,HJe5_pfNm,EUhDYhnWO,r1A5wb0Bm,S1tvLLBV7,HkqTw-CB7,rkfLTbbSX,BkLJ1iwBX,BkJVpW-H7,HkdpgyHH7,HkJnJKj4X,SkRlLLSV7,rkrjyYo4m,H1hyTwAE7,Hkc9ktj4X,r1ViuTz47,r11CnDRVQ,H1n5_pf4X,Hk8Rx1rSX,SkNgUIBE7,SkcCCcvHQ,Sk5C2PRE7,E31jeyqpM,92HJtH5cV,rJ7Q6Z-B7,H1NybJHB7,nio9QP4Ty,J8f8f0jIX,H13iOCL4z,B1pfxTOtb,G62cytcLb,7B0W0AQyO,UeLl7ZVeh,75IWxyObn,FTT0P82zx,KlYzlRe82,r14U746B7,PridefulAffixTracker,3adqlFNy2"},"transformRequest":[null],"transformResponse":[null],"timeout":15000,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"crossdomain":true},"code":"ECONNABORTED"}
app.083a595c.js:1 promisesWagoCallsComplete
app.083a595c.js:1 promisesWagoDataCallsComplete
app.083a595c.js:1 no data received for r1_GTZbHm
app.083a595c.js:1 no data received for ryBp05DHX
app.083a595c.js:1 no data received for SyGtPbRHm
app.083a595c.js:1 no data received for slraid1
app.083a595c.js:1 no data received for HJe5_pfNm
app.083a595c.js:1 no data received for EUhDYhnWO
app.083a595c.js:1 no data received for r1A5wb0Bm
app.083a595c.js:1 no data received for S1tvLLBV7
app.083a595c.js:1 no data received for HkqTw-CB7
app.083a595c.js:1 no data received for rkfLTbbSX
app.083a595c.js:1 no data received for BkLJ1iwBX
app.083a595c.js:1 no data received for BkJVpW-H7
app.083a595c.js:1 no data received for HkdpgyHH7
app.083a595c.js:1 no data received for HkJnJKj4X
app.083a595c.js:1 no data received for SkRlLLSV7
app.083a595c.js:1 no data received for rkrjyYo4m
app.083a595c.js:1 no data received for H1hyTwAE7
app.083a595c.js:1 no data received for Hkc9ktj4X
app.083a595c.js:1 no data received for r1ViuTz47
app.083a595c.js:1 no data received for r11CnDRVQ
app.083a595c.js:1 no data received for H1n5_pf4X
app.083a595c.js:1 no data received for Hk8Rx1rSX
app.083a595c.js:1 no data received for SkNgUIBE7
app.083a595c.js:1 no data received for SkcCCcvHQ
app.083a595c.js:1 no data received for Sk5C2PRE7
app.083a595c.js:1 no data received for E31jeyqpM
app.083a595c.js:1 no data received for 92HJtH5cV
app.083a595c.js:1 no data received for rJ7Q6Z-B7
app.083a595c.js:1 no data received for H1NybJHB7
app.083a595c.js:1 no data received for nio9QP4Ty
app.083a595c.js:1 no data received for J8f8f0jIX
app.083a595c.js:1 no data received for H13iOCL4z
app.083a595c.js:1 no data received for B1pfxTOtb
app.083a595c.js:1 no data received for G62cytcLb
app.083a595c.js:1 no data received for 7B0W0AQyO
app.083a595c.js:1 no data received for UeLl7ZVeh
app.083a595c.js:1 no data received for 75IWxyObn
app.083a595c.js:1 no data received for FTT0P82zx
app.083a595c.js:1 no data received for KlYzlRe82
app.083a595c.js:1 no data received for r14U746B7
app.083a595c.js:1 no data received for PridefulAffixTracker
app.083a595c.js:1 no data received for 3adqlFNy2
app.083a595c.js:1 writeAddonData
app.083a595c.js:1 {"message":"timeout of 15000ms exceeded","name":"Error","stack":"Error: timeout of 15000ms exceeded\n    at e.exports (app://./js/chunk-vendors.a271e257.js:6:94796)\n    at XMLHttpRequest.d.ontimeout (app://./js/chunk-vendors.a271e257.js:52:56769)","config":{"url":"https://data.wago.io/api/check/weakauras","method":"get","headers":{"Accept":"application/json, text/plain, */*","Identifier":"aa812adf","api-key":"2QYa13gza1DMgthIF8BHALUc2EJLK475uhwiMBfHJ7ojLvFPR6359oc1hYEHlJtI"},"params":{"ids":"r1_GTZbHm,ryBp05DHX,SyGtPbRHm,slraid1,HJe5_pfNm,EUhDYhnWO,r1A5wb0Bm,S1tvLLBV7,HkqTw-CB7,rkfLTbbSX,BkLJ1iwBX,BkJVpW-H7,HkdpgyHH7,HkJnJKj4X,SkRlLLSV7,rkrjyYo4m,H1hyTwAE7,Hkc9ktj4X,r1ViuTz47,r11CnDRVQ,H1n5_pf4X,Hk8Rx1rSX,SkNgUIBE7,SkcCCcvHQ,Sk5C2PRE7,E31jeyqpM,92HJtH5cV,rJ7Q6Z-B7,H1NybJHB7,nio9QP4Ty,J8f8f0jIX,H13iOCL4z,B1pfxTOtb,G62cytcLb,7B0W0AQyO,UeLl7ZVeh,75IWxyObn,FTT0P82zx,KlYzlRe82,r14U746B7,PridefulAffixTracker,3adqlFNy2"},"transformRequest":[null],"transformResponse":[null],"timeout":15000,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"crossdomain":true},"code":"ECONNABORTED"}
app.083a595c.js:1 promisesWagoCallsComplete
app.083a595c.js:1 promisesWagoDataCallsComplete
app.083a595c.js:1 no data received for r1_GTZbHm
app.083a595c.js:1 no data received for ryBp05DHX
app.083a595c.js:1 no data received for SyGtPbRHm
app.083a595c.js:1 no data received for slraid1
app.083a595c.js:1 no data received for HJe5_pfNm
app.083a595c.js:1 no data received for EUhDYhnWO
app.083a595c.js:1 no data received for r1A5wb0Bm
app.083a595c.js:1 no data received for S1tvLLBV7
app.083a595c.js:1 no data received for HkqTw-CB7
app.083a595c.js:1 no data received for rkfLTbbSX
app.083a595c.js:1 no data received for BkLJ1iwBX
app.083a595c.js:1 no data received for BkJVpW-H7
app.083a595c.js:1 no data received for HkdpgyHH7
app.083a595c.js:1 no data received for HkJnJKj4X
app.083a595c.js:1 no data received for SkRlLLSV7
app.083a595c.js:1 no data received for rkrjyYo4m
app.083a595c.js:1 no data received for H1hyTwAE7
app.083a595c.js:1 no data received for Hkc9ktj4X
app.083a595c.js:1 no data received for r1ViuTz47
app.083a595c.js:1 no data received for r11CnDRVQ
app.083a595c.js:1 no data received for H1n5_pf4X
app.083a595c.js:1 no data received for Hk8Rx1rSX
app.083a595c.js:1 no data received for SkNgUIBE7
app.083a595c.js:1 no data received for SkcCCcvHQ
app.083a595c.js:1 no data received for Sk5C2PRE7
app.083a595c.js:1 no data received for E31jeyqpM
app.083a595c.js:1 no data received for 92HJtH5cV
app.083a595c.js:1 no data received for rJ7Q6Z-B7
app.083a595c.js:1 no data received for H1NybJHB7
app.083a595c.js:1 no data received for nio9QP4Ty
app.083a595c.js:1 no data received for J8f8f0jIX
app.083a595c.js:1 no data received for H13iOCL4z
app.083a595c.js:1 no data received for B1pfxTOtb
app.083a595c.js:1 no data received for G62cytcLb
app.083a595c.js:1 no data received for 7B0W0AQyO
app.083a595c.js:1 no data received for UeLl7ZVeh
app.083a595c.js:1 no data received for 75IWxyObn
app.083a595c.js:1 no data received for FTT0P82zx
app.083a595c.js:1 no data received for KlYzlRe82
app.083a595c.js:1 no data received for r14U746B7
app.083a595c.js:1 no data received for PridefulAffixTracker
app.083a595c.js:1 no data received for 3adqlFNy2
app.083a595c.js:1 

**WeakAuras Version:**
```
/run print(WeakAuras.versionString) in-game.
```  version 3.2.2

**WeakAuras Errors:**
```
1. Install https://mods.curse.com/addons/wow/BugSack
2. Install https://mods.curse.com/addons/wow/bug-grabber
3. Try to do whatever it is you're having a problem with again
4. Check your minimap for an icon that looks like a bag.  Is it green, or is it red?
   • GREEN
      • WeakAuras is working correctly.
      • Either you found a behavioral bug, or you are just doing it wrong :)
      • Explain the steps you took, and we will try to figure out what happened.
   • RED 
     • There are error messages. Click on the red bag to see them.
     • Copy & Paste here all of the error messages (there may be more than one, click the 'previous' button on the dialog to see previous ones
```

**Describe the bug**
A clear and concise description of what the bug is.
loaded up WA companion, and it fails to show any of my WA's. Hit "Fetch Updates" and it says "Can't Read Wago Answer."
Tried Uninstall/Reinstall and did nothing to help.
**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.
to be able to see my WA's to update them if need be, of course haha!


**Screenshots**
If applicable, add screenshots to help explain your problem.

![Screenshot (2)](https://user-images.githubusercontent.com/80860768/111551058-f867a500-8744-11eb-9179-602bc5950880.png)

**Include a .zip file containing:**
`%programfiles%\World of Warcraft\_retail_\WTF\Account\<AccountName>\SavedVariables\WeakAuras.lua`
AND
`%appdata%\weakauras-companion\config.json`

[WeakAuras.zip](https://github.com/WeakAuras/WeakAuras-Companion/files/6160334/WeakAuras.zip)

[config.zip](https://github.com/WeakAuras/WeakAuras-Companion/files/6160393/config.zip)

**Comment by mrbuds** [comment]
Either you have network issue, or wago api have a down time, but it's not a bug in weakauras companion
