### ISSUE TITLE
Update Auras as default

### ISSUE THREAD

**Issue by NLZ** [WeakAuras/WeakAuras-Companion#98]
Currently the default import mode is Create a Copy.
If the Update Auras mode is generally safe to use then I suggest making that the default, as I think the use case is usually more fit to that; its less likely that someone wants to keep a copy of the old auras to tinker with them, they are more likely updating the fast changing auras like Causese's T23 one.

Edit: how do I change the label? :)

**Comment by emptyrivers** [comment]
It's unfortunate that Github doesn't support moving issues, as this is in the wrong project. So, I've created a duplicate issue in the WeakAuras project.
